#!/usr/bin/env bash
# creature-word-bomb-sfx.sh — concrete poetry glitchfest WITH chiptune SFX
#
# v2 of creature-word-bomb.sh:
# - Uses wibwob CLI syntax (not curl/JSON) for all commands
# - Plays chiptune SFX hits synced to each visual event
# - SFX generated by gen-sfx.py (run first if sfx/ dir missing)
#
# DEV NOTE: shell command ergonomics
# ────────────────────────────────────
# PREFER this (CLI syntax):
#   wibwob primer.open --filePath "/path/file.txt" --x 5 --y 3
#   wibwob figlet.open --text "HELLO" --font doom
#   wibwob cmd desktop.clear-all
#   wibwob theme.set --name wibwob-phosphor
#   wibwob screenshot > capture.txt
#
# AVOID this (raw curl/JSON — only needed for /windows/batch):
#   curl -s -X POST $API/commands/run -H '...' -d '{"id":"primer.open","args":{...}}'
#
# SFX playback:
#   sfx "path.wav"              — fire-and-forget (backgrounds ffplay)
#   sfx "path.wav" && sleep N   — sound + pause for human eye
#
# Batch positioning (no CLI verb yet, curl required):
#   wibwob windows | jq '[...build ops...]' | curl ... -d @-
#
# MP3 files also work: sfx "path.mp3"
# Any audio ffplay can handle works as an SFX source.
#
# FLAGS:
#   --record     Wrap in asciinema recording → .cast file
#   --export     After recording, render .cast → .gif + mix audio → .mp3 → .mp4
#   --render-audio  Just render the SFX mix to .mp3 (no visual run)

set -e
cd "$(dirname "$0")/../.."

# ── Parse flags ──
DO_RECORD=false
DO_EXPORT=false
RENDER_AUDIO_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --record) DO_RECORD=true ;;
    --export) DO_RECORD=true; DO_EXPORT=true ;;
    --render-audio) RENDER_AUDIO_ONLY=true ;;
  esac
done

W="bun run src/cli/wibwob.ts"
SMEAR="python3 .pi/skills/vj-timeline/scripts/smear.py"
DIR="scratch/captures/wordbomb-sfx-$(date +%s)"
mkdir -p "$DIR"
API="http://127.0.0.1:8099"
SFX="scratch/cli-experiments/sfx"
JGS="/Users/james/Repos/symbient-skills/skills/joan-stark-ascii-art/examples"
CUES_FILE="$DIR/cues.tsv"
START_TIME=""
WW="microapps-private/wibwob-primers/primers"

# Generate SFX if missing
if [ ! -f "$SFX/hit-word.wav" ]; then
  echo "Generating SFX..."
  REPO_ROOT="$PWD" uv run scratch/cli-experiments/gen-sfx.py "$SFX"
fi
if [ ! -f "$SFX/boom-cartoon.wav" ]; then
  echo "Generating explosion SFX..."
  REPO_ROOT="$PWD" uv run scratch/cli-experiments/gen-explosions.py "$SFX"
fi
if [ ! -f "$SFX/hit-arrange.wav" ]; then
  echo "Generating arrange SFX..."
  REPO_ROOT="$PWD" uv run scratch/cli-experiments/gen-arrange.py "$SFX"
fi
if [ ! -f "$SFX/fin-melody.wav" ]; then
  echo "Generating fin melody..."
  REPO_ROOT="$PWD" uv run scratch/cli-experiments/gen-fin-melody.py "$SFX"
fi

# Pre-render voice lines as WAV (say -o renders to file, then convert)
VOICE_DIR="$SFX/voice"
mkdir -p "$VOICE_DIR"
render_voice() {
  local voice="$1" text="$2" name="$3"
  local wav="$VOICE_DIR/${name}.wav"
  if [ ! -f "$wav" ]; then
    say -v "$voice" "$text" -o "$VOICE_DIR/${name}.aiff"
    ffmpeg -y -i "$VOICE_DIR/${name}.aiff" "$wav" 2>/dev/null
    rm -f "$VOICE_DIR/${name}.aiff"
  fi
}
render_voice "Samantha" "wib" "v-wib"
render_voice "Daniel" "wob" "v-wob"
render_voice "Wobble" "presents" "v-presents"
render_voice "Zarvox" "the menagerie" "v-menagerie"
render_voice "Bad News" "corruption" "v-corruption"
render_voice "Whisper" "shear" "v-shear"
render_voice "Trinoids" "deep glitch" "v-deep-glitch"
render_voice "Boing" "the word bomb" "v-word-bomb"
render_voice "Bells" "destruction" "v-destruction"
render_voice "Cellos" "fin" "v-fin"

# SFX player — also logs timestamp + path to cues.tsv for audio rendering
epoch_ms() { python3 -c "import time; print(int(time.time()*1000))"; }
sfx() {
  ffplay -nodisp -autoexit "$1" 2>/dev/null &
  # Log cue for offline mix
  if [ -n "$START_TIME" ]; then
    NOW=$(epoch_ms)
    OFFSET=$(( NOW - START_TIME ))
    echo -e "${OFFSET}\t${1}" >> "$CUES_FILE"
  fi
}

# Batch position helper — still needs curl (no CLI batch verb)
batch() { curl -s -X POST "$API/windows/batch" -H 'Content-Type: application/json' -d "$1" >/dev/null; }

# ── Render audio only mode ──
if [ "$RENDER_AUDIO_ONLY" = true ] && [ -f "$2" ]; then
  echo "Rendering audio from cues: $2"
  uv run scratch/cli-experiments/mix-sfx-track.py "$2" "$DIR/soundtrack.mp3"
  exit 0
fi

# ── Start asciinema recording if requested ──
if [ "$DO_RECORD" = true ]; then
  CAST_FILE="$DIR/recording.cast"
  echo "Recording with asciinema → $CAST_FILE"
  # Re-exec ourselves inside asciinema, without --record to avoid recursion
  exec asciinema rec "$CAST_FILE" -c "bash $0"
fi

echo "═══ CREATURE WORD BOMB — WITH SFX ═══"
echo "Dir: $DIR"
# Use shared recording start time if available (syncs cues with cast timestamps)
START_TIME="${WIBWOB_RECORD_START_MS:-$(epoch_ms)}"
echo ""

# ────────────────────────────────────────────────────────
# PHASE 0: INTRO — wib & wob presents...
# ────────────────────────────────────────────────────────

echo "  Phase 0: INTRO"

$W cmd desktop.clear-all 2>&1 >/dev/null
sleep 0.3
$W theme.set --name wibwob-dark 2>&1 >/dev/null
sleep 0.5

# WibWob dual portrait — centred
sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/wibbwob-dual-portrait.txt" --x 55 --y 3 2>&1 >/dev/null
sleep 0.8

# "wib" — figlet + say
sfx "$SFX/hit-word.wav"
sfx "$VOICE_DIR/v-wib.wav"
$W figlet.open --text "wib" --font doom 2>&1 >/dev/null
sleep 0.2
# Position it left of centre
WIB_ID=$($W windows 2>/dev/null | jq -r '[.[] | select(.appType=="wibwob.figlet")][-1].id')
[ -n "$WIB_ID" ] && batch "{\"ops\":[{\"id\":$WIB_ID,\"left\":20,\"top\":22,\"width\":40,\"height\":10}]}"
sleep 0.6

# "&" — tiny connector
sfx "$SFX/hit-word.wav"
$W figlet.open --text "&" --font small 2>&1 >/dev/null
sleep 0.2
AMP_ID=$($W windows 2>/dev/null | jq -r '[.[] | select(.appType=="wibwob.figlet")][-1].id')
[ -n "$AMP_ID" ] && batch "{\"ops\":[{\"id\":$AMP_ID,\"left\":62,\"top\":24,\"width\":12,\"height\":7}]}"
sleep 0.4

# "wob" — figlet + say
sfx "$SFX/hit-word.wav"
sfx "$VOICE_DIR/v-wob.wav"
$W figlet.open --text "wob" --font banner 2>&1 >/dev/null
sleep 0.2
WOB_ID=$($W windows 2>/dev/null | jq -r '[.[] | select(.appType=="wibwob.figlet")][-1].id')
[ -n "$WOB_ID" ] && batch "{\"ops\":[{\"id\":$WOB_ID,\"left\":76,\"top\":22,\"width\":45,\"height\":10}]}"
sleep 0.8

# "presents..." — figlet + say
sfx "$SFX/hit-word.wav"
sfx "$VOICE_DIR/v-presents.wav"
$W figlet.open --text "presents..." --font small 2>&1 >/dev/null
sleep 0.2
PRES_ID=$($W windows 2>/dev/null | jq -r '[.[] | select(.appType=="wibwob.figlet")][-1].id')
[ -n "$PRES_ID" ] && batch "{\"ops\":[{\"id\":$PRES_ID,\"left\":55,\"top\":34,\"width\":50,\"height\":7}]}"

sleep 2.0
echo "    ↳ wib & wob presents... — PAUSE"

# ────────────────────────────────────────────────────────
# PHASE 1: THE MENAGERIE
# ────────────────────────────────────────────────────────

sfx "$SFX/hit-clear.wav"
$W cmd desktop.clear-all 2>&1 >/dev/null
sleep 0.4

sfx "$SFX/hit-theme.wav"
$W theme.set --name wibwob-dark-nord 2>&1 >/dev/null
sleep 0.5

sfx "$VOICE_DIR/v-menagerie.wav"
echo "  Phase 1: THE MENAGERIE"

# Joan Stark animals — each with a sparkle hit
sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/cat-0000-3.txt" --x 2 --y 2 2>&1 >/dev/null
sleep 0.4

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/butterfly-0000-3.txt" --x 60 --y 1 2>&1 >/dev/null
sleep 0.4

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/baby-dragon-0000.txt" --x 110 --y 3 2>&1 >/dev/null
sleep 0.4

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/frog-0000-3.txt" --x 30 --y 18 2>&1 >/dev/null
sleep 0.4

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/black-widow-spider-0000.txt" --x 140 --y 20 2>&1 >/dev/null
sleep 0.3

# WibWob primers
sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/cat-in-space.txt" --x 80 --y 12 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/awoooo.txt" --x 5 --y 30 2>&1 >/dev/null
sleep 0.3

# Title words
sfx "$SFX/hit-word.wav"
$W figlet.open --text "SPAWN" --font shadow 2>&1 >/dev/null
sleep 0.3
sfx "$SFX/hit-word.wav"
$W figlet.open --text "ZOO" --font banner 2>&1 >/dev/null
sleep 0.3

# Position the figlets
FIDS=$($W windows 2>/dev/null | jq -r '.[] | select(.appType=="wibwob.figlet") | .id')
IDX=0; OPS="["
for id in $FIDS; do
  [ $IDX -gt 0 ] && OPS+=","
  if [ $IDX -eq 0 ]; then
    OPS+="{\"id\":$id,\"left\":50,\"top\":0,\"width\":50,\"height\":10}"
  else
    OPS+="{\"id\":$id,\"left\":120,\"top\":30,\"width\":40,\"height\":9}"
  fi
  IDX=$((IDX + 1))
done
OPS+="]"
sfx "$SFX/hit-arrange.wav"
batch "{\"ops\":$OPS}"

sleep 1.7
echo "    ↳ animals + primers — PAUSE"
$W screenshot > "$DIR/phase1-menagerie.txt" 2>/dev/null

# ────────────────────────────────────────────────────────
# PHASE 2: CORRUPTION
# ────────────────────────────────────────────────────────

sfx "$VOICE_DIR/v-corruption.wav"
echo "  Phase 2: CORRUPTION"

sfx "$SFX/hit-glitch.wav"
$SMEAR "$DIR/phase1-menagerie.txt" --mode glitch --intensity 0.4 --seed 666 \
  --out "$DIR/phase1-glitched.txt"
sleep 0.3

sfx "$SFX/hit-clear.wav"
$W cmd desktop.clear-all 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-theme.wav"
$W theme.set --name wibwob-phosphor 2>&1 >/dev/null
sleep 0.3

# Glitched backdrop
$W primer.open --filePath "$PWD/$DIR/phase1-glitched.txt" --x 0 --y 0 2>&1 >/dev/null
sleep 0.2

# Layer creatures + primers
sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/devil-terminal.txt" --x 55 --y 5 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/chaos-vs-order.txt" --x 5 --y 25 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/cat-rainbow-factory.txt" --x 120 --y 15 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/4-line-owl-0000.txt" --x 100 --y 2 2>&1 >/dev/null
sleep 0.2

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/4-line-bats-0000.txt" --x 40 --y 35 2>&1 >/dev/null
sleep 0.2

# Words
sfx "$SFX/hit-word.wav"
$W figlet.open --text "MUTATE" --font slant 2>&1 >/dev/null
sleep 0.3
sfx "$SFX/hit-word.wav"
$W figlet.open --text "FERAL" --font doom 2>&1 >/dev/null
sleep 0.3

FIDS2=$($W windows 2>/dev/null | jq -r '.[] | select(.appType=="wibwob.figlet") | .id')
IDX=0; OPS2="["
for id in $FIDS2; do
  [ $IDX -gt 0 ] && OPS2+=","
  if [ $IDX -eq 0 ]; then
    OPS2+="{\"id\":$id,\"left\":2,\"top\":1,\"width\":55,\"height\":11}"
  else
    OPS2+="{\"id\":$id,\"left\":130,\"top\":35,\"width\":48,\"height\":10}"
  fi
  IDX=$((IDX + 1))
done
OPS2+="]"
sfx "$SFX/hit-arrange.wav"
batch "{\"ops\":$OPS2}"

sleep 1.7
echo "    ↳ devil + chaos + owls — PAUSE"
$W screenshot > "$DIR/phase2-corruption.txt" 2>/dev/null

# ────────────────────────────────────────────────────────
# PHASE 3: SHEAR
# ────────────────────────────────────────────────────────

sfx "$VOICE_DIR/v-shear.wav"
echo "  Phase 3: SHEAR"

sfx "$SFX/hit-glitch.wav"
$SMEAR "$DIR/phase2-corruption.txt" --mode shear --skew 4 \
  --out "$DIR/phase2-sheared.txt"
sleep 0.3

sfx "$SFX/hit-clear.wav"
$W cmd desktop.clear-all 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-theme.wav"
$W theme.set --name wibwob-dark-pastel 2>&1 >/dev/null
sleep 0.3

$W primer.open --filePath "$PWD/$DIR/phase2-sheared.txt" --x 0 --y 0 2>&1 >/dev/null
sleep 0.2

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/ascii-draws-itself.txt" --x 70 --y 8 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/butterfly-0000-5.txt" --x 10 --y 15 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/frog-0000-6.txt" --x 130 --y 10 2>&1 >/dev/null
sleep 0.2

# Art window
$W cmd art.open 2>&1 >/dev/null
sleep 0.2
ART_ID=$(curl -s "$API/state" | jq -r '.windows[] | select(.kind=="art") | .id')
[ -n "$ART_ID" ] && batch "{\"ops\":[{\"id\":$ART_ID,\"left\":90,\"top\":25,\"width\":65,\"height\":20}]}"

# 5 words
WORDS3=("LIQUID" "BONE" "DRIP" "NERVE" "VOID")
FONTS3=("doom" "mini" "gothic" "digital" "shadow")
FX3=(0 50 105 145 70)
FY3=(0 8 1 40 55)
FW3=(48 38 52 32 42)
FH3=(10 8 11 8 10)

for i in $(seq 0 4); do
  sfx "$SFX/hit-word.wav"
  $W figlet.open --text "${WORDS3[$i]}" --font "${FONTS3[$i]}" 2>&1 >/dev/null
  sleep 0.2
done
sleep 0.3

FIDS3=$($W windows 2>/dev/null | jq -r '.[] | select(.appType=="wibwob.figlet") | .id')
IDX=0; OPS3="["
for id in $FIDS3; do
  [ $IDX -ge 5 ] && break
  [ $IDX -gt 0 ] && OPS3+=","
  OPS3+="{\"id\":$id,\"left\":${FX3[$IDX]},\"top\":${FY3[$IDX]},\"width\":${FW3[$IDX]},\"height\":${FH3[$IDX]}}"
  IDX=$((IDX + 1))
done
OPS3+="]"
sfx "$SFX/hit-arrange.wav"
batch "{\"ops\":$OPS3}"

sleep 1.7
echo "    ↳ sheared + 5 words — PAUSE"
$W screenshot > "$DIR/phase3-shear.txt" 2>/dev/null

# ────────────────────────────────────────────────────────
# PHASE 4: DEEP GLITCH
# ────────────────────────────────────────────────────────

sfx "$VOICE_DIR/v-deep-glitch.wav"
echo "  Phase 4: DEEP GLITCH"

sfx "$SFX/hit-glitch.wav"
$SMEAR "$DIR/phase3-shear.txt" --mode glitch --intensity 0.6 --seed 13 \
  --out "$DIR/phase3-deepglitch.txt"
sleep 0.3

sfx "$SFX/hit-clear.wav"
$W cmd desktop.clear-all 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-theme.wav"
$W theme.set --name wibwob-phosphor 2>&1 >/dev/null
sleep 0.3

$W primer.open --filePath "$PWD/$DIR/phase3-deepglitch.txt" --x 0 --y 0 2>&1 >/dev/null
sleep 0.2

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/cat-0000-5.txt" --x 5 --y 5 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/cat-cat.txt" --x 140 --y 28 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/brain-loop.txt" --x 80 --y 20 2>&1 >/dev/null
sleep 0.2

# 5 more words
WORDS4=("PULSE" "TEETH" "HAZE" "SILK" "FOAM")
FONTS4=("big" "gothic" "speed" "thin" "script")
FX4=(60 15 115 40 130)
FY4=(1 28 15 50 58)
FW4=(48 50 35 40 55)
FH4=(12 11 8 9 12)

for i in $(seq 0 4); do
  sfx "$SFX/hit-word.wav"
  $W figlet.open --text "${WORDS4[$i]}" --font "${FONTS4[$i]}" 2>&1 >/dev/null
  sleep 0.2
done
sleep 0.3

FIDS4=$($W windows 2>/dev/null | jq -r '.[] | select(.appType=="wibwob.figlet") | .id')
IDX=0; OPS4="["
for id in $FIDS4; do
  [ $IDX -ge 5 ] && break
  [ $IDX -gt 0 ] && OPS4+=","
  OPS4+="{\"id\":$id,\"left\":${FX4[$IDX]},\"top\":${FY4[$IDX]},\"width\":${FW4[$IDX]},\"height\":${FH4[$IDX]}}"
  IDX=$((IDX + 1))
done
OPS4+="]"
sfx "$SFX/hit-arrange.wav"
batch "{\"ops\":$OPS4}"

sleep 1.7
echo "    ↳ deep glitch + 10 words — PAUSE"
$W screenshot > "$DIR/phase4-deepglitch.txt" 2>/dev/null

# ────────────────────────────────────────────────────────
# PHASE 5: THE WORD BOMB
# ────────────────────────────────────────────────────────

sfx "$VOICE_DIR/v-word-bomb.wav"
echo "  Phase 5: THE WORD BOMB"

sfx "$SFX/hit-glitch.wav"
$SMEAR "$DIR/phase4-deepglitch.txt" --mode shear --skew 2 \
  --out "$DIR/phase4-final-shear.txt"
$SMEAR "$DIR/phase4-final-shear.txt" --mode glitch --intensity 0.35 --seed 42 \
  --out "$DIR/phase4-double-xform.txt"
sleep 0.3

sfx "$SFX/hit-clear.wav"
$W cmd desktop.clear-all 2>&1 >/dev/null
sleep 0.3

sfx "$SFX/hit-theme.wav"
$W theme.set --name wibwob-dark-pastel 2>&1 >/dev/null
sleep 0.3

# Palimpsest backdrop
$W primer.open --filePath "$PWD/$DIR/phase4-double-xform.txt" --x 0 --y 0 2>&1 >/dev/null
sleep 0.2

# Final creature fragments
sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/cat-0000-7.txt" --x 145 --y 3 2>&1 >/dev/null
sleep 0.2
sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$JGS/butterfly-0000-4.txt" --x 3 --y 38 2>&1 >/dev/null
sleep 0.2
sfx "$SFX/hit-art.wav"
$W primer.open --filePath "$PWD/$WW/cat-in-space.txt" --x 75 --y 30 2>&1 >/dev/null
sleep 0.3

# THE 20 WORDS — with escalating stinger
FINAL_WORDS=("LIQUID" "BONE" "DRIP" "WIB" "WOB" "VOID" "PULSE" "NERVE" "FLUX" "RAW" "TEETH" "HAZE" "SILK" "FOAM" "ECHO" "OOZE" "GRID" "ASH" "WARM" "MEAT")
FINAL_FONTS=("doom" "mini" "slant" "banner" "banner" "shadow" "big" "digital" "doom" "lean" "gothic" "speed" "thin" "script" "graffiti" "block" "mini" "digital" "small" "lean")
FX=(0 55 105 2 30 130 70 148 40 8 90 115 58 25 80 140 12 100 45 160)
FY=(0 5 2 12 20 8 28 55 35 48 15 42 56 62 45 32 22 60 4 50)
FW=(52 40 55 30 35 42 48 30 38 45 50 35 40 55 48 32 36 42 38 20)
FH=(10 8 11 7 9 10 12 8 9 10 11 8 9 12 10 9 8 9 8 7)

# Fire the stinger at the start of the word bomb
sfx "$SFX/stinger-finale.wav"

for i in $(seq 0 19); do
  sfx "$SFX/hit-word.wav"
  $W figlet.open --text "${FINAL_WORDS[$i]}" --font "${FINAL_FONTS[$i]}" 2>&1 >/dev/null
  sleep 0.08
done
sleep 0.3

# Batch position all 20
ALL_IDS=$($W windows 2>/dev/null | jq -r '.[] | select(.appType=="wibwob.figlet") | .id')
IDX=0; FINAL_OPS="["
for id in $ALL_IDS; do
  [ $IDX -ge 20 ] && break
  [ $IDX -gt 0 ] && FINAL_OPS+=","
  FINAL_OPS+="{\"id\":$id,\"left\":${FX[$IDX]},\"top\":${FY[$IDX]},\"width\":${FW[$IDX]},\"height\":${FH[$IDX]}}"
  IDX=$((IDX + 1))
done
FINAL_OPS+="]"
sfx "$SFX/hit-arrange.wav"
batch "{\"ops\":$FINAL_OPS}"

sleep 2.4
echo "    ↳ 20 figlets + stinger — HOLD"

$W screenshot > "$DIR/final.txt" 2>/dev/null

# ── Save the mega arrangement for human — plain + smeared ──
cp "$DIR/final.txt" "$DIR/mega-arrangement.txt"
$SMEAR "$DIR/final.txt" --mode glitch --intensity 0.5 --seed 77 \
  --out "$DIR/mega-arrangement-smeared.txt"
open "$DIR/mega-arrangement.txt"
open "$DIR/mega-arrangement-smeared.txt"
echo "    ↳ opened plain + smeared arrangement in Finder"
sleep 1.5

# ────────────────────────────────────────────────────────
# PHASE 6: DESTRUCTION — explosions, everything dies
# ────────────────────────────────────────────────────────

sfx "$VOICE_DIR/v-destruction.wav"
echo "  Phase 6: DESTRUCTION"

# Boom sounds FIRST, then close — sync the bang to the visual death
# Wave 1 — cartoon boom
ALL_WIN=$($W windows -q 2>/dev/null)
TOTAL=$(echo "$ALL_WIN" | wc -l | tr -d ' ')
THIRD=$(( (TOTAL + 2) / 3 ))

sfx "$SFX/boom-cartoon.wav"
sleep 0.05
IDX=0
for id in $ALL_WIN; do
  [ $IDX -ge $THIRD ] && break
  $W window $id close 2>&1 >/dev/null
  IDX=$((IDX + 1))
done
sleep 0.6

# Wave 2 — crackle + zap
sfx "$SFX/boom-crackle.wav"
sfx "$SFX/boom-zap.wav"
sleep 0.05
IDX=0; SKIP=0
for id in $ALL_WIN; do
  SKIP=$((SKIP + 1))
  [ $SKIP -le $THIRD ] && continue
  [ $IDX -ge $THIRD ] && break
  $W window $id close 2>&1 >/dev/null
  IDX=$((IDX + 1))
done
sleep 0.6

# Wave 3 — low boom, kill everything
sfx "$SFX/boom-low.wav"
sleep 0.05
$W cmd desktop.clear-all 2>&1 >/dev/null
sleep 0.6

# THE BIG ONE — empty desktop, final boom
sfx "$SFX/boom-final.wav"
sleep 1.2

# ────────────────────────────────────────────────────────
# PHASE 7: FIN — shark + title card on empty black
# ────────────────────────────────────────────────────────

sfx "$VOICE_DIR/v-fin.wav"
echo "  Phase 7: FIN"

$W theme.set --name wibwob-dark 2>&1 >/dev/null
sleep 0.5

# Micromelody starts — shark and title timed to the notes
sfx "$SFX/fin-melody.wav"

# Note 1 (Bb4, t=0.0s) — shark swims in
$W primer.open --filePath "$JGS/shark-0000-2.txt" --x 70 --y 12 2>&1 >/dev/null
sleep 0.5

# Note 2 (Gb4, t=0.5s) — fin. appears
$W figlet.open --text "fin." --font small 2>&1 >/dev/null
sleep 0.5

# Position FIN under the shark
FIN_ID=$($W windows 2>/dev/null | jq -r '.[] | select(.appType=="wibwob.figlet") | .id')
[ -n "$FIN_ID" ] && batch "{\"ops\":[{\"id\":$FIN_ID,\"left\":80,\"top\":28,\"width\":30,\"height\":7}]}"

sleep 2.0
echo "    ↳ 🦈 fin."

$W screenshot > "$DIR/fin.txt" 2>/dev/null

# Clear for loop
sleep 0.5
$W cmd desktop.clear-all 2>&1 >/dev/null

echo ""
echo "═══ CREATURE WORD BOMB (SFX) COMPLETE ═══"
echo "8 phases: INTRO → MENAGERIE → CORRUPTION → SHEAR → DEEP GLITCH → WORD BOMB → DESTRUCTION → FIN"

# ── Render mixed audio track from logged cues ──
if [ -f "$CUES_FILE" ]; then
  NCUES=$(wc -l < "$CUES_FILE" | tr -d ' ')
  echo "Rendering $NCUES SFX cues → soundtrack.mp3"
  uv run scratch/cli-experiments/mix-sfx-track.py "$CUES_FILE" "$DIR/soundtrack.mp3" 2>&1
fi

# ── Export pipeline: .cast → .gif, .cast + .mp3 → .mp4 ──
if [ "$DO_EXPORT" = true ] && [ -f "$DIR/recording.cast" ]; then
  echo "Rendering .cast → .gif"
  agg "$DIR/recording.cast" "$DIR/recording.gif" --cols 180 --rows 51
  echo "  → $DIR/recording.gif"

  if [ -f "$DIR/soundtrack.mp3" ]; then
    echo "Compositing .gif + .mp3 → .mp4"
    ffmpeg -y -i "$DIR/recording.gif" -i "$DIR/soundtrack.mp3" \
      -c:v libx264 -pix_fmt yuv420p -crf 23 \
      -c:a aac -b:a 192k -shortest \
      "$DIR/creature-word-bomb.mp4" 2>/dev/null
    echo "  → $DIR/creature-word-bomb.mp4"
  fi
fi

echo "Files in $DIR/"
ls -la "$DIR/"
