// Auto-generated terminal overlay for "automata-dnb" shader
// Source: automata-dnb.glsl
// Blend mode: luminance
// Generated by make-overlay.py
//
// This shader blends the music visualisation pattern with terminal
// text from Ghostty's iChannel0. Text stays readable; dark/empty
// areas show the underlying music pattern.

// ── Original shader (mainImage renamed to _musicPattern) ──────────

// Cellular Automata DnB — pseudo-automata patterns for drum & bass
// R: large cells (reese), G: small cells (stabs), B: edge noise (breaks), A: smooth field (atmo)

float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float cellNoise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    float a = hash(i);
    float b = hash(i + vec2(1, 0));
    float c = hash(i + vec2(0, 1));
    float d = hash(i + vec2(1, 1));
    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

// Pseudo cellular automaton — thresholded noise that evolves in steps
float automaton(vec2 uv, float time, float scale, float stepRate) {
    float t = floor(time * stepRate);  // discrete time steps
    vec2 p = uv * scale;
    
    // Sample neighborhood (simplified CA-like behavior)
    float center = cellNoise(p + t * 0.1);
    float north  = cellNoise(p + vec2(0, 1.0/scale) + t * 0.1);
    float east   = cellNoise(p + vec2(1.0/scale, 0) + t * 0.1);
    
    // Rule: alive if neighbors differ enough (edge detection)
    float alive = step(0.3, abs(center - north) + abs(center - east));
    return alive * center;  // modulate by original value for gradients
}

void _musicPattern(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;
    
    // R: Reese bass — large cells, slow evolution
    float reese = automaton(uv, iTime, 3.0, 2.0);
    reese = smoothstep(0.1, 0.6, reese);
    
    // G: Stabs — small cells, medium speed
    float stab = automaton(uv + 0.37, iTime, 7.0, 4.0);
    stab = pow(stab, 0.8);
    
    // B: Breaks — tiny cells, fast, very rhythmic
    float brk = automaton(uv + 0.71, iTime, 12.0, 8.0);
    brk = step(0.4, brk);  // hard trigger
    
    // A: Atmosphere — smooth blend, slow
    float atmo = cellNoise(uv * 2.0 + iTime * 0.1);
    atmo = atmo * atmo;
    
    fragColor = vec4(reese, stab, brk, atmo);
}


// ── Terminal overlay wrapper ──────────────────────────────────────

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;

    // Sample terminal text
    vec4 term = texture(iChannel0, uv);

    // Sample music pattern
    vec4 viz;
    _musicPattern(viz, fragCoord);

    // Luminance blend: text stays readable, viz fills dark areas
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float mask = smoothstep(0.05, 0.35, textMask);
    fragColor = mix(viz * 0.6, term, mask);
    fragColor.a = 1.0;
}
