// Auto-generated terminal overlay for "cineShader-Lava-lite_16step-3tap" shader
// Source: cineShader-Lava-lite_16step-3tap.glsl
// Blend mode: luminance
// Generated by make-overlay.py
//
// This shader blends the music visualisation pattern with terminal
// text from Ghostty's iChannel0. Text stays readable; dark/empty
// areas show the underlying music pattern.

// ── Original shader (mainImage renamed to _musicPattern) ──────────

// Lava lite — variation B: 16 steps + 3-tap normals + early out
// Aggressive march reduction, cheaper normals, 2x2 blocks (sharper than A)

#define BLACK_BLEND_THRESHOLD .15
#define COLOR_SPEED 0.07
#define MOVEMENT_SPEED 0.07

float opSmoothUnion(float d1, float d2, float k) {
    float h = clamp(0.5 + 0.5*(d2-d1)/k, 0.0, 1.0);
    return mix(d2, d1, h) - k*h*(1.0-h);
}

float map(vec3 p) {
    float d = 2.0;
    for (int i = 0; i < 6; i++) {
        float fi = float(i);
        float time = iTime * (fract(fi * 412.531 + 0.513) - 0.5) * 2.0;
        vec3 offset = sin(time*MOVEMENT_SPEED + fi * vec3(52.5126, 64.62744, 632.25)) * vec3(2.0, 2.0, 0.8);
        float radius = mix(0.6, 1.2, fract(fi * 412.531 + 0.5124));
        d = opSmoothUnion(length(p + offset) - radius, d, 0.5);
    }
    return d;
}

void _musicPattern(out vec4 fragColor, in vec2 fragCoord) {
    vec2 snapped = floor(fragCoord / 2.0) * 2.0 + 1.0;
    vec2 uv = snapped/iResolution.xy;
    vec3 rayOri = vec3((uv - 0.5) * vec2(iResolution.x/iResolution.y, 1.0) * 6.0, 3.0);
    vec3 rayDir = vec3(0.0, 0.0, -1.0);

    float depth = 0.0;
    vec3 p;
    float d;
    for (int i = 0; i < 16; i++) {
        p = rayOri + rayDir * depth;
        d = map(p);
        depth += d;
        if (d < 1e-4 || depth > 5.0) break;
    }

    vec4 term = texture(iChannel0, fragCoord / iResolution.xy);

    if (depth >= 5.0) {
        // Background tint — same color cycle as blobs, depth-fogged like OG
        float fog = exp(-5.0 * 0.15);  // 0.47 — matches OG's miss depth
        vec3 tint = (0.5 + 0.5*cos((iTime*COLOR_SPEED*3.0) + uv.xyx*2.0 + vec3(0,2,4))) * fog * 0.3;
        fragColor = vec4(term.rgb * 0.2 + tint, term.a);
        return;
    }

    // 3-tap forward difference normals (cheaper than 4-tap tetrahedron)
    const float h = 3e-4;
    vec3 n = normalize(vec3(
        map(p+vec3(h,0,0)) - d,
        map(p+vec3(0,h,0)) - d,
        map(p+vec3(0,0,h)) - d));

    float b = max(0.0, dot(n, vec3(0.577)));
    vec3 col = (0.5 + 0.5*cos((b + iTime*COLOR_SPEED*3.0) + uv.xyx*2.0 + vec3(0,2,4))) * (0.85 + b*0.35);
    col *= exp(-depth * 0.15);

    // Soft blend: lava only in truly dark areas, text always readable
    float lum = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float alpha = smoothstep(BLACK_BLEND_THRESHOLD + 0.15, BLACK_BLEND_THRESHOLD, lum);
    fragColor = vec4(mix(term.rgb, term.rgb * 0.5 + col * 0.25, alpha), term.a);
}


// ── Terminal overlay wrapper ──────────────────────────────────────

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;

    // Sample terminal text
    vec4 term = texture(iChannel0, uv);

    // Sample music pattern
    vec4 viz;
    _musicPattern(viz, fragCoord);

    // Luminance blend: text stays readable, viz fills dark areas
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float mask = smoothstep(0.05, 0.35, textMask);
    fragColor = mix(viz * 0.6, term, mask);
    fragColor.a = 1.0;
}
