// Auto-generated terminal overlay for "cineShader-Lava-lite_slow4-quarterrez" shader
// Source: cineShader-Lava-lite_slow4-quarterrez.glsl
// Blend mode: luminance
// Generated by make-overlay.py
//
// This shader blends the music visualisation pattern with terminal
// text from Ghostty's iChannel0. Text stays readable; dark/empty
// areas show the underlying music pattern.

// ── Original shader (mainImage renamed to _musicPattern) ──────────

// Lava lite D — OG look, 1/3 speed, 4 blobs, quarter res
// Keeps original blend logic + depth fog + normals. Just fewer blobs, slower, chunkier.

#define BLACK_BLEND_THRESHOLD .4
#define COLOR_SPEED 0.033
#define MOVEMENT_SPEED 0.033

float opSmoothUnion(float d1, float d2, float k) {
    float h = clamp(0.5 + 0.5*(d2-d1)/k, 0.0, 1.0);
    return mix(d2, d1, h) - k*h*(1.0-h);
}

float sdSphere(vec3 p, float s) {
    return length(p) - s;
}

float map(vec3 p) {
    float d = 2.0;
    for (int i = 0; i < 4; i++) {
        float fi = float(i);
        float time = iTime * (fract(fi * 412.531 + 0.513) - 0.5) * 2.0;
        d = opSmoothUnion(
            sdSphere(p + sin(time*MOVEMENT_SPEED + fi * vec3(52.5126, 64.62744, 632.25)) * vec3(2.0, 2.0, 0.8),
                     mix(0.7, 1.4, fract(fi * 412.531 + 0.5124))),
            d, 0.4);
    }
    return d;
}

vec3 calcNormal(in vec3 p) {
    const float h = 1e-5;
    const vec2 k = vec2(1,-1);
    return normalize(k.xyy*map(p+k.xyy*h) + k.yyx*map(p+k.yyx*h) +
                     k.yxy*map(p+k.yxy*h) + k.xxx*map(p+k.xxx*h));
}

void _musicPattern(out vec4 fragColor, in vec2 fragCoord) {
    vec2 snapped = floor(fragCoord / 4.0) * 4.0 + 2.0;
    vec2 uv = snapped / iResolution.xy;

    vec3 rayOri = vec3((uv - 0.5) * vec2(iResolution.x/iResolution.y, 1.0) * 6.0, 3.0);
    vec3 rayDir = vec3(0.0, 0.0, -1.0);

    float depth = 0.0;
    vec3 p;
    for (int i = 0; i < 64; i++) {
        p = rayOri + rayDir * depth;
        float dist = map(p);
        depth += dist;
        if (dist < 1e-6) break;
    }

    depth = min(6.0, depth);
    vec3 n = calcNormal(p);
    float b = max(0.0, dot(n, vec3(0.577)));
    vec3 col = (0.5 + 0.5 * cos((b + iTime*0.03) + uv.xyx*2.0 + vec3(0,2,4))) * (0.85 + b*0.35);
    col *= exp(-depth * 0.15);

    vec4 terminalColor = texture(iChannel0, fragCoord.xy / iResolution.xy);
    float alpha = step(length(terminalColor.rgb), BLACK_BLEND_THRESHOLD);
    vec3 blendedColor = mix(terminalColor.rgb * 1.0, col.rgb * 0.3, alpha);

    fragColor = vec4(blendedColor, terminalColor.a);
}


// ── Terminal overlay wrapper ──────────────────────────────────────

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;

    // Sample terminal text
    vec4 term = texture(iChannel0, uv);

    // Sample music pattern
    vec4 viz;
    _musicPattern(viz, fragCoord);

    // Luminance blend: text stays readable, viz fills dark areas
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float mask = smoothstep(0.05, 0.35, textMask);
    fragColor = mix(viz * 0.6, term, mask);
    fragColor.a = 1.0;
}
