// wibwob-ambient.glsl — ambient figlet words baked as bit-packed GLSL constants
// AUTO-GENERATED by scripts/gen-figlet-shader.sh — re-run to change words/fonts/timing
// Terminal: 142×81   Words: void/banner3, chaos/banner3, order/banner3, flux/banner3, drift/banner3, pulse/banner3, glitch/banner3, echo/banner3

// ── Timing tunables ──────────────────────────────────────────
const float WORD_INTERVAL  = 5.0;   // seconds between each word
const float FADE_IN        = 1.0;    // fade-in duration
const float DISPLAY_TIME   = 8.0;   // fully visible duration
const float FADE_OUT       = 2.0;    // fade-out duration

// ── Grid ─────────────────────────────────────────────────────
const float COLS           = 142.0;
const float ROWS           = 81.0;
const float GRID_OPACITY   = 0.12;   // cell grid darkness
const float BG_DIM         = 0.45;   // dim terminal content so words pop

// ── Gradient ─────────────────────────────────────────────────
const bool  GRAD_ON        = true;
const float GRAD_OPACITY   = 0.18;
const float GRAD_ANGLE     = 0.0;    // 0=N→S  90=W→E  45=diagonal
const vec3  C_A = vec3(0.796, 0.651, 0.969) * 0.5;  // mauve top
const vec3  C_B = vec3(0.537, 0.706, 0.980) * 0.5;  // blue  bottom

// ── Word colours (Catppuccin Mocha accent palette) ────────────
const vec3 WORD_COLORS[8] = vec3[8](
    vec3(0.796, 0.651, 0.969),   // mauve
    vec3(0.537, 0.706, 0.980),   // blue
    vec3(0.953, 0.545, 0.659),   // pink
    vec3(0.651, 0.890, 0.631),   // green
    vec3(0.976, 0.886, 0.686),   // yellow
    vec3(0.584, 0.910, 0.898),   // teal
    vec3(0.808, 0.624, 0.988),   // lavender
    vec3(0.949, 0.655, 0.408)    // peach
);

// ── Baked word dimensions ─────────────────────────────────────
const int WORD_COUNT = 8;
const int WORD_W[8] = int[8](35, 48, 49, 38, 43, 47, 52, 38);
const int WORD_H[8] = int[8](7, 7, 7, 7, 7, 7, 7, 7);

// ── Bit-packed cell bitmaps ───────────────────────────────────
// Layout: WORD_BITS[word * MAX_H * 2 + row * 2 + 0] = cols 0-31
//         WORD_BITS[word * MAX_H * 2 + row * 2 + 1] = cols 32-63
// Generated from: void/banner3, chaos/banner3, order/banner3, flux/banner3, drift/banner3, pulse/banner3, glitch/banner3, echo/banner3
// void / banner3  (35×7)
// chaos / banner3  (48×7)
// order / banner3  (49×7)
// flux / banner3  (38×7)
// drift / banner3  (43×7)
// pulse / banner3  (47×7)
// glitch / banner3  (52×7)
// echo / banner3  (38×7)
const uint WORD_BITS[128] = uint[128](
    0xFEF3F983u,
    0x00000001u,
    0x06660D83u,
    0x00000003u,
    0x06660D83u,
    0x00000003u,
    0x06660D83u,
    0x00000003u,
    0x06660CC6u,
    0x00000003u,
    0x06660C6Cu,
    0x00000003u,
    0xFEF3F838u,
    0x00000001u,
    0x00000000u,
    0x00000000u,
    0xC1C3067Eu,
    0x00003F1Fu,
    0x636306C3u,
    0x000061B0u,
    0x66330603u,
    0x000001B0u,
    0x6C1BFE03u,
    0x00003F30u,
    0x6FFB0603u,
    0x00006030u,
    0x6C1B06C3u,
    0x000061B0u,
    0xCC1B067Eu,
    0x00003F1Fu,
    0x00000000u,
    0x00000000u,
    0xCFF3FCFEu,
    0x00007FBFu,
    0xD8360D83u,
    0x0000C180u,
    0xD8360D83u,
    0x0000C180u,
    0xD833FD83u,
    0x00007F8Fu,
    0xD8318D83u,
    0x00003180u,
    0xD8330D83u,
    0x00006180u,
    0xCFF60CFEu,
    0x0000C1BFu,
    0x00000000u,
    0x00000000u,
    0x360C06FFu,
    0x00000018u,
    0x660C0603u,
    0x0000000Cu,
    0xC60C0603u,
    0x00000006u,
    0x860C063Fu,
    0x00000003u,
    0xC60C0603u,
    0x00000006u,
    0x660C0603u,
    0x0000000Cu,
    0x33F9FE03u,
    0x00000018u,
    0x00000000u,
    0x00000000u,
    0xFEF3FCFFu,
    0x000003FDu,
    0x06660D83u,
    0x00000060u,
    0x06660D83u,
    0x00000060u,
    0x7E63FD83u,
    0x00000060u,
    0x06618D83u,
    0x00000060u,
    0x06630D83u,
    0x00000060u,
    0x06F60CFFu,
    0x00000060u,
    0x00000000u,
    0x00000000u,
    0xC0360CFFu,
    0x00003FCFu,
    0x60360D83u,
    0x000000D8u,
    0x60360D83u,
    0x000000C0u,
    0xC0360CFFu,
    0x00000FCFu,
    0x00360C03u,
    0x000000D8u,
    0x60360C03u,
    0x000000D8u,
    0xCFF3F803u,
    0x00003FCFu,
    0x00000000u,
    0x00000000u,
    0xFF780C7Eu,
    0x00060CFCu,
    0x18300CC3u,
    0x00060D86u,
    0x18300C03u,
    0x00060C06u,
    0x18300DE3u,
    0x0007FC06u,
    0x18300CC3u,
    0x00060C06u,
    0x18300CC3u,
    0x00060D86u,
    0x187BFC7Eu,
    0x00060CFCu,
    0x00000000u,
    0x00000000u,
    0xE60CFCFFu,
    0x0000000Fu,
    0x360D8603u,
    0x00000018u,
    0x360C0603u,
    0x00000018u,
    0x37FC063Fu,
    0x00000018u,
    0x360C0603u,
    0x00000018u,
    0x360D8603u,
    0x00000018u,
    0xE60CFCFFu,
    0x0000000Fu,
    0x00000000u,
    0x00000000u
);

// ── Helpers ───────────────────────────────────────────────────
float hash(float n) { return fract(sin(n) * 43758.5453); }

bool getBit(int wi, int row, int col) {
    if (row < 0 || col < 0 || row >= WORD_H[wi] || col >= WORD_W[wi]) return false;
    int base = wi * 16 + row * 2;
    uint bits = col < 32 ? WORD_BITS[base] : WORD_BITS[base + 1];
    return ((bits >> uint(col < 32 ? col : col - 32)) & 1u) == 1u;
}

// Alpha for word wi at current time (staggered by wi * WORD_INTERVAL)
float wordAlpha(int wi) {
    float period = WORD_INTERVAL * float(WORD_COUNT);
    float t = mod(iTime - float(wi) * WORD_INTERVAL, period);
    float total = FADE_IN + DISPLAY_TIME + FADE_OUT;
    if (t < 0.0 || t > total) return 0.0;
    if (t < FADE_IN)                      return t / FADE_IN;
    if (t < FADE_IN + DISPLAY_TIME)       return 1.0;
    return 1.0 - (t - FADE_IN - DISPLAY_TIME) / FADE_OUT;
}

// Hash-based cell position — changes each full cycle
vec2 wordPos(int wi) {
    float cycle = floor(iTime / (WORD_INTERVAL * float(WORD_COUNT)));
    float fx = hash(float(wi) * 13.7 + cycle * 97.3);
    float fy = hash(float(wi) * 29.1 + cycle * 43.7 + 53.0);
    float maxC = COLS - float(WORD_W[wi]) - 2.0;
    float maxR = ROWS - float(WORD_H[wi]) - 2.0;
    return vec2(floor(fx * maxC) + 1.0, floor(fy * maxR) + 1.0);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 cell    = round(iResolution.xy / vec2(COLS, ROWS));
    vec2 uv      = fragCoord / iResolution.xy;
    vec2 cpos    = mod(fragCoord, cell) / cell;
    vec2 cellXY  = floor(fragCoord / cell);  // which cell we're in

    // Terminal content, dimmed so words pop
    vec4 col = texture(iChannel0, uv);
    col.rgb *= BG_DIM;

    // Gradient
    if (GRAD_ON) {
        float rad  = GRAD_ANGLE * 3.14159265 / 180.0;
        vec2  dir  = vec2(sin(rad), cos(rad));
        float t    = dot(uv - 0.5, dir) + 0.5;
        vec3  grad = mix(C_A, C_B, clamp(t, 0.0, 1.0));
        col.rgb = mix(col.rgb, grad, GRAD_OPACITY);
    }

    // Render each word
    for (int wi = 0; wi < WORD_COUNT; wi++) {
        float alpha = wordAlpha(wi);
        if (alpha < 0.001) continue;

        vec2  origin = wordPos(wi);
        ivec2 offset = ivec2(cellXY) - ivec2(origin);

        if (getBit(wi, offset.y, offset.x)) {
            col.rgb = mix(col.rgb, WORD_COLORS[wi], alpha * 0.10);
        }
    }

    // Cell grid on top
    float gx = step(1.0 - 1.0 / cell.x, cpos.x);
    float gy = step(1.0 - 1.0 / cell.y, cpos.y);
    col.rgb *= 1.0 - max(gx, gy) * GRID_OPACITY;

    fragColor = col;
}
