// wibwob-cell-grid.glsl — cell-aligned ASCII grid overlay
// AUTO-GENERATED by scripts/cell-shader.sh — re-run to update after resize
// Terminal at generation time: 142×81

const float COLS           = 142.0;
const float ROWS           = 81.0;
const float GRID_OPACITY   = 0.20;   // grid line darkness at cell edges

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    // Snap to integer cell size: Ghostty rounds cell_px internally, but
    // iResolution may include 1-2px OS rounding remainder (drawable = COLS*cell + r).
    // round() recovers the true integer cell dimensions.
    vec2 cell = round(iResolution.xy / vec2(COLS, ROWS));
    vec2 uv   = fragCoord / iResolution.xy;

    // Position within the current cell, 0..1
    vec2 cpos = mod(fragCoord, cell) / cell;

    vec4 col = texture(iChannel0, uv);

    // Grid lines: 1px at right + bottom edge of each cell
    float gx = step(1.0 - 1.0 / cell.x, cpos.x);
    float gy = step(1.0 - 1.0 / cell.y, cpos.y);
    col.rgb *= 1.0 - max(gx, gy) * GRID_OPACITY;

    fragColor = col;
}
