#!/usr/bin/env python3
"""
make-overlay.py — Wrap a music shader as a Ghostty terminal overlay.

Takes a GLSL shader that writes to fragColor via mainImage() and wraps it
so the shader pattern blends with terminal text from iChannel0. Text stays
readable; dark/empty areas show the music visualisation.

Usage:
    python3 make-overlay.py <input.glsl> [output.glsl]
    python3 make-overlay.py --all          # wrap all shaders in shader-music/
    python3 make-overlay.py --list         # show available shaders

If output is omitted, writes to shaders/<name>-overlay.glsl

Blend modes (set via --blend):
    luminance  (default) — text mask from terminal brightness, viz in dark areas
    additive   — shader adds colour on top of terminal
    multiply   — shader darkens terminal (moody/noir)
    screen     — shader lightens terminal (dreamy/glowy)
"""

import argparse
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.join(SCRIPT_DIR, "../..")
SHADER_MUSIC_DIR = os.path.join(SCRIPT_DIR, "../shader-music")
SHADERS_OUTPUT_DIR = os.path.join(REPO_ROOT, "shaders")

BLEND_TEMPLATES = {
    "luminance": """\
    // Luminance blend: text stays readable, viz fills dark areas
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float mask = smoothstep(0.05, 0.35, textMask);
    fragColor = mix(viz * 0.6, term, mask);
    fragColor.a = 1.0;
""",
    "additive": """\
    // Additive blend: shader adds colour on top of terminal
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float vizStrength = 0.4 * (1.0 - smoothstep(0.1, 0.5, textMask));
    fragColor = term + viz * vizStrength;
    fragColor.a = 1.0;
""",
    "multiply": """\
    // Multiply blend: shader darkens terminal (moody)
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float vizStrength = 1.0 - smoothstep(0.1, 0.5, textMask);
    vec4 mulled = vec4(term.rgb * (viz.rgb * 0.5 + 0.5), 1.0);
    fragColor = mix(term, mulled, vizStrength * 0.7);
    fragColor.a = 1.0;
""",
    "screen": """\
    // Screen blend: shader lightens terminal (dreamy/glowy)
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float vizStrength = 0.35 * (1.0 - smoothstep(0.2, 0.6, textMask));
    vec4 screened = vec4(1.0 - (1.0 - term.rgb) * (1.0 - viz.rgb * 0.5), 1.0);
    fragColor = mix(term, screened, vizStrength);
    fragColor.a = 1.0;
""",
}


def find_shaders():
    """Find all music shaders in shader-music/ directory (including subdirs)."""
    shaders = []
    for root, dirs, files in os.walk(SHADER_MUSIC_DIR):
        # Skip hidden dirs
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for f in sorted(files):
            if f.endswith(".glsl") and not f.startswith("."):
                shaders.append(os.path.join(root, f))
    return sorted(shaders)


def wrap_shader(source_path: str, blend: str = "luminance") -> str:
    """Wrap a music shader as a Ghostty terminal overlay."""
    with open(source_path) as f:
        source = f.read()

    name = os.path.basename(source_path).replace(".glsl", "")

    # Rename mainImage → _musicPattern to avoid redefinition
    # Handle both `void mainImage(out vec4 fragColor, in vec2 fragCoord)`
    # and variations with different whitespace
    wrapped_source = re.sub(
        r'\bvoid\s+mainImage\s*\(',
        'void _musicPattern(',
        source
    )

    blend_code = BLEND_TEMPLATES.get(blend, BLEND_TEMPLATES["luminance"])

    overlay = f"""\
// Auto-generated terminal overlay for "{name}" shader
// Source: {os.path.basename(source_path)}
// Blend mode: {blend}
// Generated by make-overlay.py
//
// This shader blends the music visualisation pattern with terminal
// text from Ghostty's iChannel0. Text stays readable; dark/empty
// areas show the underlying music pattern.

// ── Original shader (mainImage renamed to _musicPattern) ──────────

{wrapped_source}

// ── Terminal overlay wrapper ──────────────────────────────────────

void mainImage(out vec4 fragColor, in vec2 fragCoord) {{
    vec2 uv = fragCoord / iResolution.xy;

    // Sample terminal text
    vec4 term = texture(iChannel0, uv);

    // Sample music pattern
    vec4 viz;
    _musicPattern(viz, fragCoord);

{blend_code}}}
"""
    return overlay


def output_path_for(source_path: str) -> str:
    """Generate output path in shaders/ directory.
    
    For subdirectory shaders (e.g. ghostty-shaders/galaxy.glsl),
    flattens to shaders/galaxy-overlay.glsl (basename only).
    """
    name = os.path.basename(source_path).replace(".glsl", "")
    return os.path.join(SHADERS_OUTPUT_DIR, f"{name}-overlay.glsl")


def main():
    parser = argparse.ArgumentParser(description="Wrap music shaders as Ghostty terminal overlays")
    parser.add_argument("input", nargs="?", help="Input GLSL file")
    parser.add_argument("output", nargs="?", help="Output GLSL file (default: shaders/<name>-overlay.glsl)")
    parser.add_argument("--blend", default="luminance",
                        choices=list(BLEND_TEMPLATES.keys()),
                        help="Blend mode (default: luminance)")
    parser.add_argument("--all", action="store_true", help="Wrap all shaders in shader-music/")
    parser.add_argument("--list", action="store_true", help="List available shaders")
    args = parser.parse_args()

    if args.list:
        shaders = find_shaders()
        print(f"Available shaders in {SHADER_MUSIC_DIR}:")
        for s in shaders:
            name = os.path.basename(s)
            out = output_path_for(s)
            exists = "✅" if os.path.exists(out) else "  "
            print(f"  {exists} {name}")
        return

    if args.all:
        shaders = find_shaders()
        os.makedirs(SHADERS_OUTPUT_DIR, exist_ok=True)
        for s in shaders:
            out = output_path_for(s)
            overlay = wrap_shader(s, args.blend)
            with open(out, "w") as f:
                f.write(overlay)
            print(f"  ✅ {os.path.basename(s)} → {os.path.relpath(out, REPO_ROOT)}")
        print(f"\n{len(shaders)} overlays written to {os.path.relpath(SHADERS_OUTPUT_DIR, REPO_ROOT)}/")
        return

    if not args.input:
        parser.print_help()
        sys.exit(1)

    source = args.input
    if not os.path.exists(source):
        # Try relative to shader-music/
        alt = os.path.join(SHADER_MUSIC_DIR, source)
        if os.path.exists(alt):
            source = alt
        else:
            print(f"❌ Not found: {source}")
            sys.exit(1)

    os.makedirs(SHADERS_OUTPUT_DIR, exist_ok=True)
    out = args.output or output_path_for(source)
    overlay = wrap_shader(source, args.blend)
    with open(out, "w") as f:
        f.write(overlay)
    print(f"✅ {os.path.basename(source)} → {out}")
    print(f"   Blend: {args.blend}")
    print(f"   Activate: bash scripts/ghostty-shader.sh on {os.path.basename(out).replace('.glsl', '')}")


if __name__ == "__main__":
    main()
