// Auto-generated terminal overlay for "tft" shader
// Source: tft.glsl
// Blend mode: luminance
// Generated by make-overlay.py
//
// This shader blends the music visualisation pattern with terminal
// text from Ghostty's iChannel0. Text stays readable; dark/empty
// areas show the underlying music pattern.

// ── Original shader (mainImage renamed to _musicPattern) ──────────

/** Size of TFT "pixels" */
float resolution = 4.0;

/** Strength of effect */
float strength = 0.5;

void _scanline(inout vec3 color, vec2 uv)
{
    float scanline = step(1.2, mod(uv.y * iResolution.y, resolution));
    float grille   = step(1.2, mod(uv.x * iResolution.x, resolution));
    color *= max(1.0 - strength, scanline * grille);
}

void _musicPattern(out vec4 fragColor, in vec2 fragCoord)
{
    vec2 uv = fragCoord.xy / iResolution.xy;
    vec3 color = texture(iChannel0, uv).rgb;

    _scanline(color, uv);

    fragColor.xyz = color;
    fragColor.w   = 1.0;
}


// ── Terminal overlay wrapper ──────────────────────────────────────

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;

    // Sample terminal text
    vec4 term = texture(iChannel0, uv);

    // Sample music pattern
    vec4 viz;
    _musicPattern(viz, fragCoord);

    // Luminance blend: text stays readable, viz fills dark areas
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float mask = smoothstep(0.05, 0.35, textMask);
    fragColor = mix(viz * 0.6, term, mask);
    fragColor.a = 1.0;
}
