// Auto-generated terminal overlay for "voronoi-lofi" shader
// Source: voronoi-lofi.glsl
// Blend mode: luminance
// Generated by make-overlay.py
//
// This shader blends the music visualisation pattern with terminal
// text from Ghostty's iChannel0. Text stays readable; dark/empty
// areas show the underlying music pattern.

// ── Original shader (mainImage renamed to _musicPattern) ──────────

// Voronoi Lo-fi — organic cell patterns, slow drifting
// R: cell distance (bass), G: cell ID hash (keys), B: edge glow (vinyl crackle), A: slow warp (pad)

vec2 hash2(vec2 p) {
    p = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));
    return fract(sin(p) * 43758.5453);
}

// Voronoi with animated cell centers
void voronoi(vec2 uv, float time, float scale, float speed,
             out float dist, out float cellId, out float edge) {
    vec2 p = uv * scale;
    vec2 ip = floor(p);
    vec2 fp = fract(p);
    
    float minDist = 1.0;
    float minDist2 = 1.0;
    float id = 0.0;
    
    for (int y = -1; y <= 1; y++) {
        for (int x = -1; x <= 1; x++) {
            vec2 neighbor = vec2(float(x), float(y));
            vec2 point = hash2(ip + neighbor);
            // Animate cell centers — slow organic drift
            point = 0.5 + 0.5 * sin(time * speed + 6.2831 * point);
            vec2 diff = neighbor + point - fp;
            float d = length(diff);
            
            if (d < minDist) {
                minDist2 = minDist;
                minDist = d;
                id = dot(ip + neighbor, vec2(7.0, 113.0));
            } else if (d < minDist2) {
                minDist2 = d;
            }
        }
    }
    
    dist = minDist;
    cellId = fract(sin(id) * 43758.5453);
    edge = minDist2 - minDist;  // thin at edges
}

void _musicPattern(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;
    
    float dist1, id1, edge1;
    float dist2, id2, edge2;
    
    // Layer 1: large slow cells (bass + keys)
    voronoi(uv, iTime, 3.0, 0.3, dist1, id1, edge1);
    
    // Layer 2: smaller faster cells (crackle + pad)
    voronoi(uv + 0.5, iTime, 6.0, 0.6, dist2, id2, edge2);
    
    // R: bass — distance from cell center, inverted (closer = louder)
    float bass = 1.0 - smoothstep(0.0, 0.5, dist1);
    
    // G: keys — cell ID creates pitch variety, modulated by time
    float keys = id1 * 0.7 + 0.3 * sin(iTime * 0.4 + id1 * 6.28);
    
    // B: vinyl crackle — edge proximity, spiky
    float crackle = smoothstep(0.08, 0.0, edge1) * 0.5 + 
                    smoothstep(0.05, 0.0, edge2) * 0.5;
    
    // A: pad — slow blend of both layers
    float pad = mix(dist1, 1.0 - dist2, 0.5 + 0.5 * sin(iTime * 0.15));
    
    fragColor = vec4(bass, keys, crackle, pad);
}


// ── Terminal overlay wrapper ──────────────────────────────────────

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 uv = fragCoord / iResolution.xy;

    // Sample terminal text
    vec4 term = texture(iChannel0, uv);

    // Sample music pattern
    vec4 viz;
    _musicPattern(viz, fragCoord);

    // Luminance blend: text stays readable, viz fills dark areas
    float textMask = dot(term.rgb, vec3(0.2126, 0.7152, 0.0722));
    float mask = smoothstep(0.05, 0.35, textMask);
    fragColor = mix(viz * 0.6, term, mask);
    fragColor.a = 1.0;
}
