// AUTO-GENERATED by scripts/gen-primitives.ts — do not edit by hand. Run: bun run gen-primitives

// src/core/theme/resolver.ts
export { theme, themeName, setThemeVariant, allVariants, registerExternalTheme } from "./theme/resolver.js";

// src/core/theme/types.ts
export type { StylePair, ThemeTokens, ThemeVariant } from "./theme/types.js";

// src/core/ui-parts.ts
export { createStack, createColumns, createHeaderBar, createStatusBar, createTextBlock, createInputLine, createMessageHistory, createRule, createFigletDisplay, createAnimatedPanel } from "./ui-parts.js";
export type { Rect, UiPart, StackChild, InputLineProps, MessageHistoryEntry, MessageHistoryProps } from "./ui-parts.js";

// src/core/ui-primitives.ts
export { createScrollbar, scrollableStyle, safeSetStyle, isRightClick } from "./ui-primitives.js";

// src/core/window-chrome.ts
export { getChromeModeForWindow, contentToWindowSize } from "./window-chrome.js";
export type { ChromeMode, ContentSize, WindowSize } from "./window-chrome.js";

// src/services/animation-service.ts
export { createPreRenderedPlayer, createLivePlayer } from "../services/animation-service.js";
export type { LiveFrameGenerator, FramePlayer } from "../services/animation-service.js";

// src/services/content-measurement.ts
export { measurePrimerContent } from "../services/content-measurement.js";
