// AUTO-GENERATED by scripts/gen-primitives.ts — do not edit by hand. Run: bun run gen-primitives

// src/core/render-monitor.ts
export type { RenderMonitorHandle } from "./render-monitor.js";

// src/core/theme/resolver.ts
export { theme, themeName, setThemeVariant, allVariants, registerExternalTheme } from "./theme/resolver.js";

// src/core/theme/types.ts
export type { StylePair, ThemeTokens, ThemeVariant } from "./theme/types.js";

// src/core/ui-parts.ts
export { createStack, createRow, createColumns, createHeaderBar, createStatusBar, createTextBlock, createInputLine, createMessageHistory, createRule, createFigletDisplay, createAnimatedPanel, createCollapsibleBlock, createContentStack } from "./ui-parts.js";
export type { Rect, LayoutPart, UiPart, FlexChild, StackChild, GridChild, FlexBasis, TrackSize, AxisAlign, Alignment, Gap, InputLineProps, MessageHistoryEntry, MessageHistoryProps, CollapsibleBlockProps, CollapsibleBlockHandle, ContentStackChild, ContentStackHandle } from "./ui-parts.js";

// src/core/ui-primitives.ts
export { createScrollbar, scrollableStyle, safeSetStyle, isRightClick, createTimer, clearTimers } from "./ui-primitives.js";

// src/core/window-chrome.ts
export { getChromeModeForWindow, contentToWindowSize } from "./window-chrome.js";
export type { ChromeMode, ContentSize, WindowSize } from "./window-chrome.js";

// src/services/animation-service.ts
export { createPreRenderedPlayer, createLivePlayer } from "../services/animation-service.js";
export type { LiveFrameGenerator, FramePlayer } from "../services/animation-service.js";

// src/services/content-measurement.ts
export { measurePrimerContent } from "../services/content-measurement.js";

// src/services/monster-cam-service.ts
export { MonsterCamService } from "../services/monster-cam-service.js";
export type { MonsterCamFrame } from "../services/monster-cam-service.js";

// src/services/webcam-renderer.ts
export { renderWebcamFrame, gridToBlessedContent } from "../services/webcam-renderer.js";
export type { WebcamCell, WebcamRenderOptions } from "../services/webcam-renderer.js";
