// AUTO-GENERATED by scripts/gen-primitives.ts — do not edit directly
// Watched: src/core/*/index.ts
// Regenerate: bun scripts/gen-primitives.ts
// Parent: ARCHITECTURE.md §Shell

// src/core/render-monitor.ts
export type { RenderMonitorHandle } from "./render-monitor.js";

// src/core/theme/resolver.ts
export { theme, themeName, setThemeVariant, allVariants, registerExternalTheme } from "./theme/resolver.js";

// src/core/theme/types.ts
export type { StylePair, ThemeTokens, ThemeVariant } from "./theme/types.js";

// src/core/ui-primitives.ts
export { createScrollbar, scrollableStyle, safeSetStyle, isRightClick, createTimer, clearTimers, toEvenCellWidth, safeDestroy, safeDestroyAll } from "./ui-primitives.js";

// src/core/window-chrome.ts
export { getChromeModeForWindow, contentToWindowSize } from "./window-chrome.js";
export type { ChromeMode, ContentSize, WindowSize } from "./window-chrome.js";

// src/services/animation-service.ts
export { createPreRenderedPlayer, createLivePlayer } from "../services/animation-service.js";
export type { LiveFrameGenerator, FramePlayer } from "../services/animation-service.js";

// src/services/content-measurement.ts
export { measurePrimerContent } from "../services/content-measurement.js";

// src/services/monster-cam-service.ts
export { MonsterCamService } from "../services/monster-cam-service.js";
export type { MonsterCamFrame } from "../services/monster-cam-service.js";

// src/services/webcam-renderer.ts
export { renderWebcamFrame, gridToBlessedContent } from "../services/webcam-renderer.js";
export type { WebcamRenderOptions } from "../services/webcam-renderer.js";

// src/ui/chrome.ts
export { createLayoutStatusBar, createTextBlock, createLayoutInputLine, createMessageHistory, createLayoutRule, createFigletDisplay, createAnimatedPanel } from "../ui/chrome.js";
export type { InputLineProps, MessageHistoryEntry, MessageHistoryProps } from "../ui/chrome.js";

// src/ui/containers.ts
export { createScrollViewport, createCollapsibleBlock, createContentStack, createLayoutTabs } from "../ui/containers.js";
export type { ScrollViewportOptions, ScrollViewportHandle, CollapsibleBlockProps, CollapsibleBlockHandle, ContentStackChild, ContentStackHandle } from "../ui/containers.js";

// src/ui/layout.ts
export { createStack, createRow, pickBreakpoint, createGrid } from "../ui/layout.js";
export type { Alignment, Gap, FlexChild, GridChild, BreakpointName, BreakpointEntry, GridOptions, GridHandle } from "../ui/layout.js";

// src/ui/types.ts
export type { LayoutPart, FlexBasis, TrackSize, AxisAlign } from "../ui/types.js";
