#!/usr/bin/env bash
# @name    cell-shader
# @desc    Generate + activate a cell-aligned Ghostty shader tuned to current terminal dims
#
# Usage:  cell-shader.sh [on|off|status]
#   on     Generate GLSL with current COLS×ROWS baked in, then activate (default)
#   off    Deactivate shader
#   status Show current state + baked dims if active
#
# Why:    Ghostty sizes its window to exactly COLS×cell_w pixels, so
#         iResolution.xy / vec2(COLS,ROWS) = exact cell size in the shader.
#         This lets scanlines/grids align to actual terminal character boundaries.

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
SHADER_OUT="$REPO_ROOT/assets/shaders/wibwob-cell-grid.glsl"
SHADER_SCRIPT="$REPO_ROOT/.pi/skills/wibwobdos/scripts/ghostty-shader.sh"

# Read live terminal dims from wibwob minimap (e.g. "142x81")
dims() {
    bash "$REPO_ROOT/scripts/minimap.sh" 2>/dev/null \
        | head -1 | grep -oE '[0-9]+x[0-9]+' | head -1
}

generate() {
    local d; d="$(dims)"
    [[ -z "$d" ]] && { echo "❌ Could not read terminal dims from minimap"; exit 1; }
    local cols="${d%x*}" rows="${d#*x}"
    echo "📐 Terminal: ${cols}×${rows} — cell = iResolution / vec2(${cols}, ${rows})"

    cat > "$SHADER_OUT" << GLSL
// wibwob-cell-grid.glsl — cell-aligned ASCII grid overlay
// AUTO-GENERATED by scripts/cell-shader.sh — re-run to update after resize
// Terminal at generation time: ${cols}×${rows}

const float COLS           = ${cols}.0;
const float ROWS           = ${rows}.0;
const float GRID_OPACITY   = 0.10;   // grid line darkness at cell edges
const float SCANLINE_DARK  = 0.15;   // row-bottom scanline shadow depth
const float CELL_VIGNETTE  = 0.08;   // per-cell center-bright / edge-dark

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    // round() snaps to true integer cell size — Ghostty rounds cell_px internally
    // but iResolution may carry 1-2px OS remainder: drawable = COLS*cell_px + r
    vec2 cell = round(iResolution.xy / vec2(COLS, ROWS));
    vec2 uv   = fragCoord / iResolution.xy;

    // Position within the current cell, 0..1
    vec2 cpos = mod(fragCoord, cell) / cell;

    vec4 col = texture(iChannel0, uv);

    // Grid lines: 1px at right + bottom edge of each cell
    float gx = step(1.0 - 1.0 / cell.x, cpos.x);
    float gy = step(1.0 - 1.0 / cell.y, cpos.y);
    col.rgb *= 1.0 - max(gx, gy) * GRID_OPACITY;

    // Scanline: darken the bottom 20% of each row (aligns to character descenders)
    col.rgb *= 1.0 - smoothstep(0.80, 1.0, cpos.y) * SCANLINE_DARK;

    // Per-cell vignette: subtle centre-glow, edge-dark within each character cell
    vec2 cv = cpos * 2.0 - 1.0;
    col.rgb *= 1.0 - dot(cv * cv, vec2(0.5)) * CELL_VIGNETTE;

    fragColor = col;
}
GLSL
    echo "✅ Shader written: $SHADER_OUT"
}

case "${1:-on}" in
    on)
        generate
        bash "$SHADER_SCRIPT" on wibwob-cell-grid ;;
    off)
        bash "$SHADER_SCRIPT" off ;;
    status)
        bash "$SHADER_SCRIPT" status
        [[ -f "$SHADER_OUT" ]] && grep -E "^// Terminal|^const float (COLS|ROWS)" "$SHADER_OUT" ;;
    *)
        echo "Usage: $0 [on|off|status]" ;;
esac
