#!/usr/bin/env bash
# doc-health.sh — measures documentation system integrity
# Simplified for autoresearch. 8 binary checks, each worth 1 point = 0-8.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

SCORE=0

check() {
  if ( eval "$2" ) > /dev/null 2>&1; then
    SCORE=$((SCORE + 1))
  fi
}

# 1. Staleness — are generated outputs current?
check "staleness" "bash scripts/doc-sync.sh --check"

# 2. Script headers — all gen-* have @watches/@output/@run
check "headers" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do
    [ -f "$s" ] || continue
    for t in @watches @output @run; do
      grep -qE "^(//|#) $t" "$s" || exit 1
    done
  done
'

# 3. Back-links — outputs reference their generators
check "backlinks" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do
    [ -f "$s" ] || continue
    o=$(grep -E "^(//|#) @output" "$s" | sed "s|.*@output ||" | tr -d " ")
    [ -z "$o" ] || [ ! -f "$o" ] && continue
    grep -q "AUTO-GENERATED" "$o" || exit 1
    grep -q "Regenerate:" "$o" || exit 1
  done
'

# 4. Forward-links — outputs have Parent reference
check "parents" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do
    [ -f "$s" ] || continue
    o=$(grep -E "^(//|#) @output" "$s" | sed "s|.*@output ||" | tr -d " ")
    [ -z "$o" ] || [ ! -f "$o" ] && continue
    grep -q "Parent:" "$o" || exit 1
  done
'

# 5. PD integrity — <output> paths in CAPS files exist on disk
check "pd_integrity" '
  for caps in AGENTS.md ARCHITECTURE.md SDK.md GOTCHAS.md; do
    [ -f "$caps" ] || continue
    while IFS= read -r line; do
      p=$(echo "$line" | sed "s|.*<output>||;s|</output>.*||" | grep -oE "`[^`]+`" | head -1 | tr -d "`" | awk "{print \$1}")
      [ -z "$p" ] || echo "$p" | grep -qE "bun|python|\\.\\.\\." && continue
      [ -f "$p" ] || exit 1
    done < <(grep "<output>" "$caps" 2>/dev/null || true)
  done
'

# 6. Loop circularity — script→output→back-link→parent CAPS→output ref
check "circularity" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do
    [ -f "$s" ] || continue
    o=$(grep -E "^(//|#) @output" "$s" | sed "s|.*@output ||" | tr -d " ")
    [ -z "$o" ] || [ ! -f "$o" ] && continue
    grep -q "AUTO-GENERATED by $s" "$o" || exit 1
    parent=$(grep "Parent:" "$o" | grep -oE "[A-Z]+\.md" | head -1)
    [ -z "$parent" ] || [ ! -f "$parent" ] && exit 1
    grep -q "$o" "$parent" || exit 1
  done
'

# 7. Orphan detection — no generated files whose generator is gone
check "orphans" '
  git ls-files "*.md" "*.ts" 2>/dev/null | while IFS= read -r f; do
    head -3 "$f" 2>/dev/null | grep -q "AUTO-GENERATED by" || continue
    gen=$(head -5 "$f" | grep -oE "AUTO-GENERATED by scripts/[^ ]+" | sed "s/AUTO-GENERATED by //" | sed "s/[[:space:]].*//" | head -1)
    [ -z "$gen" ] && continue
    [ -f "$gen" ] || exit 1
  done
'

# 8. Functional — COAT endpoint count matches source, skills count matches source
check "functional" '
  if [ -f COAT.md ] && [ -f src/services/control-api.ts ]; then
    src=$(grep -c "\"path\":" src/services/control-api.ts 2>/dev/null || echo 0)
    doc=$(grep -oE "Endpoints: [0-9]+" COAT.md | grep -oE "[0-9]+" | head -1 || echo 0)
    [ "$doc" -ge "$src" ] || [ "$((src - doc))" -le 2 ] || exit 1
  fi
  if [ -f .pi/skills/skills.md ]; then
    src=$(find .pi/skills -name "SKILL.md" ! -path "*/.trash/*" 2>/dev/null | wc -l | tr -d " ")
    doc=$(grep -c "^## " .pi/skills/skills.md 2>/dev/null || echo 0)
    [ "$doc" -ge "$((src - 2))" ] || exit 1
  fi
'

# 9. Parent section exists — Parent header's §section actually exists in the CAPS file
check "parent_section" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do
    [ -f "$s" ] || continue
    o=$(grep -E "^(//|#) @output" "$s" | sed "s|.*@output ||" | tr -d " ")
    [ -z "$o" ] || [ ! -f "$o" ] && continue
    parent_line=$(head -5 "$o" | grep "Parent:" | head -1)
    [ -z "$parent_line" ] && continue
    caps=$(echo "$parent_line" | grep -oE "[A-Z]+\.md" | head -1)
    section=$(echo "$parent_line" | grep -oE "§[^-]+" | sed "s/§//" | sed "s/[[:space:]]*$//" | head -1)
    [ -z "$caps" ] || [ -z "$section" ] || [ ! -f "$caps" ] && continue
    grep -qi "$section" "$caps" || exit 1
  done
'

# 10. @watches import match — declared watches contain files the script actually reads
check "watches_match" '
  for s in scripts/gen-*.ts; do
    [ -f "$s" ] || continue
    watches=$(grep -E "^// @watches" "$s" | sed "s|.*@watches ||")
    [ -z "$watches" ] && continue
    while IFS= read -r imp; do
      imp=$(echo "$imp" | tr -d "\"" | tr -d "'\'' ")
      [ -z "$imp" ] && continue
      # Check that at least one @watches entry is a prefix of this import
      matched=false
      for w in $watches; do
        echo "$imp" | grep -q "$w" && matched=true && break
      done
      [ "$matched" = true ] || exit 1
    done < <(grep -oE "readFileSync\([^)]+\)" "$s" | grep -oE "\"[^\"]+\"" | grep -v "utf" || true)
  done
'

echo "METRIC doc_health=$SCORE"
