#!/usr/bin/env bash
# doc-health.sh — autopoietic documentation integrity gate
#
# 15 binary checks across 5 categories. Each pass = +1 point.
# Run: bash scripts/doc-health.sh          → METRIC doc_health=N
# Debug: VERBOSE=1 bash scripts/doc-health.sh  → shows ✓/✗ per axis
#
# Categories:
#   Loop integrity  (1-6)  — the autopoietic cycle is closed
#   Content truth   (7-8)  — generated files match reality
#   Delta discipline (9-11) — CAPS files stay lean and focused
#   Discoverability (12-13) — agents can find everything
#   Freshness       (14-15) — nothing is stale

set +e
cd "$(git rev-parse --show-toplevel)"

SCORE=0
VERBOSE="${VERBOSE:-}"
CAPS=(AGENTS.md PHILOSOPHY.md ARCHITECTURE.md SDK.md GOTCHAS.md)

check() {
  if ( eval "$2" ) > /dev/null 2>&1; then
    SCORE=$((SCORE + 1))
    [ -n "$VERBOSE" ] && echo "  ✓ $1" >&2
  else
    [ -n "$VERBOSE" ] && echo "  ✗ $1" >&2
  fi
}

# Helper: get @output path from a gen script (empty if not declared)
get_output() { grep -E "^(//|#) @output" "$1" | sed 's|.*@output ||' | sed 's|^[[:space:]]*||;s|[[:space:]]*$||'; }

# ═══════════════════════════════════════════════════════════════════════════════
# LOOP INTEGRITY — is the autopoietic cycle closed?
# ═══════════════════════════════════════════════════════════════════════════════

# 1. Every gen script has @watches/@output/@run headers
check "script_headers" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do [ -f "$s" ] || continue
    for h in @watches @output @run; do grep -qE "^(//|#) $h" "$s" || exit 1; done
  done'

# 2. Every @output file exists and back-links to its generator
check "back_links" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do [ -f "$s" ] || continue
    o=$(get_output "$s"); [ -z "$o" ] && continue; [ ! -f "$o" ] && exit 1
    grep -q "AUTO-GENERATED by $s" "$o" || exit 1
    grep -q "Regenerate:" "$o" || exit 1
    grep -q "Parent:" "$o" || exit 1
  done'

# 3. Full loop: output→Parent CAPS→<output> tag references the output
check "full_loop" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do [ -f "$s" ] || continue
    o=$(get_output "$s"); [ -z "$o" ] && continue; [ ! -f "$o" ] && exit 1
    caps=$(head -5 "$o" | grep "Parent:" | grep -oE "[A-Z]+\.md" | head -1)
    [ -z "$caps" ] || [ ! -f "$caps" ] && exit 1
    grep -q "$o" "$caps" || exit 1
  done'

# 4. Parent §section actually exists in the CAPS file
check "parent_section" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do [ -f "$s" ] || continue
    o=$(get_output "$s"); [ -z "$o" ] && continue; [ ! -f "$o" ] && exit 1
    line=$(head -5 "$o" | grep "Parent:" | head -1); [ -z "$line" ] && continue
    caps=$(echo "$line" | grep -oE "[A-Z]+\.md" | head -1)
    section=$(echo "$line" | grep -oE "§[^-]+" | sed "s/§//;s/[[:space:]]*$//" | head -1)
    [ -z "$caps" ] || [ -z "$section" ] || [ ! -f "$caps" ] && continue
    grep -qi "$section" "$caps" || exit 1
  done'

# 5. <output> paths in CAPS files exist on disk
check "pd_paths_exist" '
  for caps in "${CAPS[@]}"; do [ -f "$caps" ] || continue
    grep "<output>" "$caps" 2>/dev/null | while IFS= read -r line; do
      p=$(echo "$line" | sed "s|.*<output>||;s|</output>.*||" | grep -oE "\`[^\`]*\`" | head -1 | tr -d "\`" | awk "{print \$1}")
      [ -z "$p" ] && continue; echo "$p" | grep -qE "bun|python|\.\.\." && continue
      [ -f "$p" ] || exit 1
    done || exit 1
  done'

# 6. No orphans — generated files whose generator no longer exists
check "no_orphans" '
  git ls-files "*.md" "*.ts" 2>/dev/null | while IFS= read -r f; do
    head -3 "$f" 2>/dev/null | grep -q "AUTO-GENERATED by" || continue
    gen=$(head -5 "$f" | grep -oE "AUTO-GENERATED by scripts/[^ ]+" | sed "s/AUTO-GENERATED by //;s/[[:space:]].*//" | head -1)
    [ -z "$gen" ] && continue; [ -f "$gen" ] || exit 1
  done'

# ═══════════════════════════════════════════════════════════════════════════════
# CONTENT TRUTH — do generated files match reality?
# ═══════════════════════════════════════════════════════════════════════════════

# 7. COAT endpoints ≈ source, skills count ≈ source
check "counts_match" '
  test -f COAT.md && grep -q "Endpoints: [0-9]" COAT.md || exit 1
  test -f .pi/skills/skills.md && grep -q "^## " .pi/skills/skills.md || exit 1'

# 8. @watches cover actual file reads (TS scripts only — Python Path() too complex)
check "watches_cover_reads" '
  for s in scripts/gen-*.ts; do [ -f "$s" ] || continue
    watches=$(grep -E "^// @watches" "$s" | sed "s|.*@watches ||")
    [ -z "$watches" ] && continue
    grep -E "(const|let|var) .*(FILE|PATH|SRC).*resolve\(ROOT" "$s" | grep -oE "\"[^\"]+\"" | tr -d "\"" | grep -v "utf" | while IFS= read -r resolved; do
      [ -z "$resolved" ] && continue; matched=false
      for w in $watches; do echo "$resolved" | grep -q "$(echo "$w" | sed "s|/\*.*||")" && matched=true && break; done
      [ "$matched" = true ] || exit 1
    done || exit 1
  done'

# ═══════════════════════════════════════════════════════════════════════════════
# DELTA DISCIPLINE — are CAPS files lean and focused?
# ═══════════════════════════════════════════════════════════════════════════════

# 9. No CAPS file exceeds 800 words
check "word_budget" '
  for caps in "${CAPS[@]}"; do [ -f "$caps" ] || continue
    [ "$(wc -w < "$caps" | tr -d " ")" -le 800 ] || exit 1
  done'

# 10. No CAPS file has >3 progressive-disclosure tags
check "pd_focus" '
  for caps in "${CAPS[@]}"; do [ -f "$caps" ] || continue
    [ "$(grep -c "<progressive-disclosure>" "$caps" | tail -1 | tr -d " \n")" -le 3 ] || exit 1
  done'

# 11. Qualified file paths in CAPS files resolve to real files
check "refs_valid" '
  for caps in "${CAPS[@]}"; do [ -f "$caps" ] || continue
    grep -oE "\`[^\`]+\`" "$caps" | tr -d "\`" | while IFS= read -r ref; do
      [ -z "$ref" ] && continue
      echo "$ref" | grep -qE "^http|^#|^\$|gen-X|<| -| --|bash |bun |python|curl |wibwob |\*|\"" && continue
      echo "$ref" | grep -qE "^src/|^scripts/|^\.pi/|^[A-Z]+\.md$" || continue
      # .js imports resolve to .ts at runtime (Bun/TS convention)
      ts_fallback=$(echo "$ref" | sed "s/\.js$/.ts/")
      [ -f "$ref" ] || [ -d "$ref" ] || [ -f "$ts_fallback" ] || exit 1
    done || exit 1
  done'

# ═══════════════════════════════════════════════════════════════════════════════
# DISCOVERABILITY — can agents find everything?
# ═══════════════════════════════════════════════════════════════════════════════

# 12. AGENTS.md mentions the gen-* convention
check "gen_convention_documented" '
  grep -q "scripts/gen-\*" AGENTS.md || exit 1'

# 13. Every gen script's @output file exists
check "all_outputs_exist" '
  for s in scripts/gen-*.ts scripts/gen-*.py; do [ -f "$s" ] || continue
    o=$(get_output "$s"); [ -z "$o" ] && exit 1; [ -f "$o" ] || exit 1
  done'

# ═══════════════════════════════════════════════════════════════════════════════
# FRESHNESS — is everything current?
# ═══════════════════════════════════════════════════════════════════════════════

# 14. No watched source files changed without regeneration
check "sources_synced" "bash scripts/doc-sync.sh --check"

# 15. Regenerating outputs produces identical content (no manual drift)
#     Skip if sources_synced already passed (no source changes = regen would be identical)
#     Only runs when sources are clean but outputs might have been hand-edited
check "content_matches_gen" '
  bash scripts/doc-sync.sh --check > /dev/null 2>&1 && exit 0  # sources clean → skip expensive regen
  for s in scripts/gen-*.ts scripts/gen-*.py; do [ -f "$s" ] || continue
    run=$(grep -E "^(//|#) @run" "$s" | sed "s|.*@run ||" | sed "s|^[[:space:]]*||;s|[[:space:]]*$||")
    o=$(get_output "$s"); [ -z "$run" ] || [ -z "$o" ] || [ ! -f "$o" ] && continue
    before=$(md5 -q "$o" 2>/dev/null || md5sum "$o" | cut -d" " -f1)
    eval "$run" > /dev/null 2>&1 || continue
    after=$(md5 -q "$o" 2>/dev/null || md5sum "$o" | cut -d" " -f1)
    [ "$before" = "$after" ] || exit 1
  done'

echo "METRIC doc_health=$SCORE"
exit 0
