#!/usr/bin/env bash
# @name    gen-figlet-shader
# @desc    Render words in figlet fonts → bit-packed GLSL → assets/shaders/wibwob-ambient.glsl
#
# Each word is converted to a binary cell grid (space=0, any char=1),
# bit-packed into uint pairs (lo=cols 0-31, hi=cols 32-63) and baked as
# GLSL constants. The shader renders them entirely on the GPU — no runtime
# figlet calls, no terminal I/O, perfectly cell-aligned.
#
# Re-run any time you change WORDS/FONTS/tunables:
#   bash scripts/gen-figlet-shader.sh && bash .pi/skills/wibwobdos/scripts/ghostty-shader.sh on wibwob-ambient

set -euo pipefail
REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"

# ── Words + fonts (paired) ────────────────────────────────────────────────────
WORDS=( void        chaos       order       flux        drift       pulse       glitch      echo       )
FONTS=( banner3     banner3     banner3     banner3     banner3     banner3     banner3     banner3    )

# ── Timing (seconds) ─────────────────────────────────────────────────────────
WORD_INTERVAL=5.0    # how often a new word appears
FADE_IN=1.0          # fade-in duration
DISPLAY_TIME=8.0     # how long word stays fully visible
FADE_OUT=2.0         # fade-out duration

# ── Terminal grid (read live from minimap) ────────────────────────────────────
DIMS=$(bash "$REPO_ROOT/scripts/minimap.sh" 2>/dev/null | head -1 | grep -oE '[0-9]+x[0-9]+' | head -1)
COLS="${DIMS%x*}"
ROWS="${DIMS#*x}"
echo "📐 Terminal: ${COLS}×${ROWS}"

# ── Bit-pack words via Python ─────────────────────────────────────────────────
JSON=$(python3 - "${WORDS[@]}" "${FONTS[@]}" << 'PYEOF'
import subprocess, sys, json

args = sys.argv[1:]
half = len(args) // 2
words = args[:half]
fonts = args[half:]

MAX_H = 8   # pad all words to this height
MAX_W = 64  # 2× uint32 per row

data = []
for word, font in zip(words, fonts):
    r = subprocess.run(['figlet', '-f', font, word], capture_output=True, text=True)
    lines = r.stdout.rstrip('\n').split('\n')
    while lines and not lines[-1].strip():
        lines.pop()
    h = len(lines)
    w = max((len(l) for l in lines), default=0)
    w = min(w, MAX_W)

    rows = []
    for i in range(MAX_H):
        line = (lines[i] if i < h else '').ljust(MAX_W)
        lo = hi = 0
        for j, c in enumerate(line[:32]):
            if c != ' ': lo |= (1 << j)
        for j, c in enumerate(line[32:64]):
            if c != ' ': hi |= (1 << j)
        rows.append([lo, hi])

    data.append({'word': word, 'font': font, 'w': w, 'h': h, 'rows': rows})

print(json.dumps(data))
PYEOF
)

# ── Generate GLSL ─────────────────────────────────────────────────────────────
OUT="$REPO_ROOT/assets/shaders/wibwob-ambient.glsl"

python3 - "$JSON" "$COLS" "$ROWS" "$WORD_INTERVAL" "$FADE_IN" "$DISPLAY_TIME" "$FADE_OUT" > "$OUT" << 'PYEOF'
import sys, json

data         = json.loads(sys.argv[1])
cols, rows   = int(sys.argv[2]), int(sys.argv[3])
interval     = float(sys.argv[4])
fade_in      = float(sys.argv[5])
display_time = float(sys.argv[6])
fade_out     = float(sys.argv[7])
n            = len(data)
MAX_H        = 8

def u(v): return f"0x{v:08X}u"

lines = []
lines.append(f"""\
// wibwob-ambient.glsl — ambient figlet words baked as bit-packed GLSL constants
// AUTO-GENERATED by scripts/gen-figlet-shader.sh — re-run to change words/fonts/timing
// Terminal: {cols}×{rows}   Words: {", ".join(d["word"]+"/"+d["font"] for d in data)}

// ── Timing tunables ──────────────────────────────────────────
const float WORD_INTERVAL  = {interval};   // seconds between each word
const float FADE_IN        = {fade_in};    // fade-in duration
const float DISPLAY_TIME   = {display_time};   // fully visible duration
const float FADE_OUT       = {fade_out};    // fade-out duration

// ── Grid ─────────────────────────────────────────────────────
const float COLS           = {cols}.0;
const float ROWS           = {rows}.0;
const float GRID_OPACITY   = 0.12;   // cell grid darkness
const float BG_DIM         = 0.45;   // dim terminal content so words pop
const float WORD_OPACITY   = 0.10;   // word brightness (0=invisible, 1=full colour)

// ── Gradient ─────────────────────────────────────────────────
const bool  GRAD_ON        = true;
const float GRAD_OPACITY   = 0.18;
const float GRAD_ANGLE     = 0.0;    // 0=N→S  90=W→E  45=diagonal
const vec3  C_A = vec3(0.796, 0.651, 0.969) * 0.5;  // mauve top
const vec3  C_B = vec3(0.537, 0.706, 0.980) * 0.5;  // blue  bottom

// ── Word colours (Catppuccin Mocha accent palette) ────────────
const vec3 WORD_COLORS[8] = vec3[8](
    vec3(0.796, 0.651, 0.969),   // mauve
    vec3(0.537, 0.706, 0.980),   // blue
    vec3(0.953, 0.545, 0.659),   // pink
    vec3(0.651, 0.890, 0.631),   // green
    vec3(0.976, 0.886, 0.686),   // yellow
    vec3(0.584, 0.910, 0.898),   // teal
    vec3(0.808, 0.624, 0.988),   // lavender
    vec3(0.949, 0.655, 0.408)    // peach
);

// ── Baked word dimensions ─────────────────────────────────────
const int WORD_COUNT = {n};
const int WORD_W[{n}] = int[{n}]({", ".join(str(d["w"]) for d in data)});
const int WORD_H[{n}] = int[{n}]({", ".join(str(d["h"]) for d in data)});

// ── Bit-packed cell bitmaps ───────────────────────────────────
// Layout: WORD_BITS[word * MAX_H * 2 + row * 2 + 0] = cols 0-31
//         WORD_BITS[word * MAX_H * 2 + row * 2 + 1] = cols 32-63
// Generated from: {", ".join(d["word"]+"/"+d["font"] for d in data)}""")

flat = []
for d in data:
    lines.append(f"// {d['word']} / {d['font']}  ({d['w']}×{d['h']})")
    for row in d['rows']:
        flat.append(u(row[0]))
        flat.append(u(row[1]))

total = n * MAX_H * 2
lines.append(f"const uint WORD_BITS[{total}] = uint[{total}](")
lines.append("    " + ",\n    ".join(flat))
lines.append(");")

lines.append("""
// ── Helpers ───────────────────────────────────────────────────
float hash(float n) { return fract(sin(n) * 43758.5453); }

bool getBit(int wi, int row, int col) {
    if (row < 0 || col < 0 || row >= WORD_H[wi] || col >= WORD_W[wi]) return false;
    int base = wi * """ + str(MAX_H * 2) + """ + row * 2;
    uint bits = col < 32 ? WORD_BITS[base] : WORD_BITS[base + 1];
    return ((bits >> uint(col < 32 ? col : col - 32)) & 1u) == 1u;
}

// Alpha for word wi at current time (staggered by wi * WORD_INTERVAL)
float wordAlpha(int wi) {
    float period = WORD_INTERVAL * float(WORD_COUNT);
    float t = mod(iTime - float(wi) * WORD_INTERVAL, period);
    float total = FADE_IN + DISPLAY_TIME + FADE_OUT;
    if (t < 0.0 || t > total) return 0.0;
    if (t < FADE_IN)                      return t / FADE_IN;
    if (t < FADE_IN + DISPLAY_TIME)       return 1.0;
    return 1.0 - (t - FADE_IN - DISPLAY_TIME) / FADE_OUT;
}

// Hash-based cell position — changes each full cycle
vec2 wordPos(int wi) {
    float cycle = floor(iTime / (WORD_INTERVAL * float(WORD_COUNT)));
    float fx = hash(float(wi) * 13.7 + cycle * 97.3);
    float fy = hash(float(wi) * 29.1 + cycle * 43.7 + 53.0);
    float maxC = COLS - float(WORD_W[wi]) - 2.0;
    float maxR = ROWS - float(WORD_H[wi]) - 2.0;
    return vec2(floor(fx * maxC) + 1.0, floor(fy * maxR) + 1.0);
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 cell    = round(iResolution.xy / vec2(COLS, ROWS));
    vec2 uv      = fragCoord / iResolution.xy;
    vec2 cpos    = mod(fragCoord, cell) / cell;
    vec2 cellXY  = floor(fragCoord / cell);  // which cell we're in

    // Terminal content, dimmed so words pop
    vec4 col = texture(iChannel0, uv);
    col.rgb *= BG_DIM;

    // Gradient
    if (GRAD_ON) {
        float rad  = GRAD_ANGLE * 3.14159265 / 180.0;
        vec2  dir  = vec2(sin(rad), cos(rad));
        float t    = dot(uv - 0.5, dir) + 0.5;
        vec3  grad = mix(C_A, C_B, clamp(t, 0.0, 1.0));
        col.rgb = mix(col.rgb, grad, GRAD_OPACITY);
    }

    // Render each word
    for (int wi = 0; wi < WORD_COUNT; wi++) {
        float alpha = wordAlpha(wi);
        if (alpha < 0.001) continue;

        vec2  origin = wordPos(wi);
        ivec2 offset = ivec2(cellXY) - ivec2(origin);

        if (getBit(wi, offset.y, offset.x)) {
            col.rgb = mix(col.rgb, WORD_COLORS[wi], alpha * WORD_OPACITY);
        }
    }

    // Cell grid on top
    float gx = step(1.0 - 1.0 / cell.x, cpos.x);
    float gy = step(1.0 - 1.0 / cell.y, cpos.y);
    col.rgb *= 1.0 - max(gx, gy) * GRID_OPACITY;

    fragColor = col;
}""")

print('\n'.join(lines))
PYEOF

echo "✅ Written: $OUT"
