// @name    gen-primitives
// @desc    Regenerate src/core/primitives.ts index from shared exports
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import ts from "typescript";

type PrimitiveGroup = {
  values: string[];
  types: string[];
};

// Resolve from script location so it works from any cwd, including git worktrees
const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const SRC_ROOT = path.join(REPO_ROOT, "src");
const OUTPUT_FILE = path.join(SRC_ROOT, "core", "primitives.ts");

const HEADER = `// AUTO-GENERATED by scripts/gen-primitives.ts — do not edit by hand. Run: bun run gen-primitives
`;

async function main(): Promise<void> {
  const files = await collectTypeScriptFiles(SRC_ROOT);
  const groups = new Map<string, PrimitiveGroup>();

  for (const filePath of files) {
    const group = await readPrimitiveExports(filePath);
    if (group.values.length === 0 && group.types.length === 0) {
      continue;
    }
    groups.set(filePath, group);
  }

  await writeFile(OUTPUT_FILE, render(groups), "utf8");
}

async function collectTypeScriptFiles(root: string): Promise<string[]> {
  const results: string[] = [];
  await walk(root, results);
  return results.sort();
}

async function walk(dirPath: string, results: string[]): Promise<void> {
  const entries = await readdir(dirPath, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === "__tests__" || entry.name === ".codex-logs") {
      continue;
    }

    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      await walk(fullPath, results);
      continue;
    }
    if (!entry.isFile()) {
      continue;
    }
    if (!fullPath.endsWith(".ts") || fullPath.endsWith(".d.ts")) {
      continue;
    }
    if (fullPath === OUTPUT_FILE || fullPath.includes(".test.") || fullPath.includes(".spec.")) {
      continue;
    }

    results.push(fullPath);
  }
}

async function readPrimitiveExports(filePath: string): Promise<PrimitiveGroup> {
  const sourceText = await readFile(filePath, "utf8");
  const sourceFile = ts.createSourceFile(filePath, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const values: string[] = [];
  const types: string[] = [];

  for (const statement of sourceFile.statements) {
    if (!hasPrimitiveTag(statement) || !hasExportModifier(statement)) {
      continue;
    }

    if (ts.isFunctionDeclaration(statement) || ts.isClassDeclaration(statement) || ts.isEnumDeclaration(statement)) {
      const name = statement.name?.text;
      if (name) {
        values.push(name);
      }
      continue;
    }

    if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        if (ts.isIdentifier(declaration.name)) {
          values.push(declaration.name.text);
        }
      }
      continue;
    }

    if (ts.isTypeAliasDeclaration(statement) || ts.isInterfaceDeclaration(statement)) {
      types.push(statement.name.text);
    }
  }

  return { values, types };
}

function hasPrimitiveTag(node: ts.Node): boolean {
  return ts.getJSDocTags(node).some(tag => tag.tagName.text === "primitive");
}

function hasExportModifier(node: ts.Node): boolean {
  return ts.canHaveModifiers(node) && ts.getModifiers(node)?.some(mod => mod.kind === ts.SyntaxKind.ExportKeyword) === true;
}

function render(groups: Map<string, PrimitiveGroup>): string {
  const blocks = Array.from(groups.entries()).map(([filePath, group]) => {
    const parts = [`// ${toRepoRelative(filePath)}`];
    const importPath = toImportPath(filePath);

    if (group.values.length > 0) {
      parts.push(`export { ${group.values.join(", ")} } from "${importPath}";`);
    }
    if (group.types.length > 0) {
      parts.push(`export type { ${group.types.join(", ")} } from "${importPath}";`);
    }

    return parts.join("\n");
  });

  return `${HEADER}\n${blocks.join("\n\n")}\n`;
}

function toImportPath(filePath: string): string {
  const fromDir = path.dirname(OUTPUT_FILE);
  const relativePath = path.relative(fromDir, filePath).replace(/\.ts$/, ".js").replaceAll(path.sep, "/");
  return relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
}

function toRepoRelative(filePath: string): string {
  return path.relative(REPO_ROOT, filePath).replaceAll(path.sep, "/");
}

await main();
