#!/usr/bin/env bash
# scripts/handover.sh — auto-generate a session handover doc from live sources.
#
# Output: tmp/session-handover-YYYY-MM-DD.md
# Runs in < 5s without the app running.
# Usage: bash scripts/handover.sh

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATE="$(date +%Y-%m-%d)"
TIME="$(date +%H:%M:%S)"
OUT="$REPO/tmp/session-handover-$DATE.md"
CURRENT_BRANCH="$(git -C "$REPO" branch --show-current 2>/dev/null || echo "(unknown)")"

mkdir -p "$REPO/tmp"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

parse_epics() {
  local filter_status="${1:-}"
  for brief in "$REPO/.planning/epics"/e*/e*-brief.md; do
    [ -f "$brief" ] || continue
    eid="$(grep    '^id:'     "$brief" | head -1 | sed 's/^id: *//')"
    title="$(grep  '^title:'  "$brief" | head -1 | sed 's/^title: *//')"
    status="$(grep '^status:' "$brief" | head -1 | sed 's/^status: *//')"
    issue="$(grep  '^issue:'  "$brief" | head -1 | sed 's/^issue: *//')"
    [ -z "$eid" ] && continue
    if [ -n "$filter_status" ]; then
      [ "$status" = "$filter_status" ] || continue
      echo "- **${eid}** — ${title}  (issue: #${issue})"
    else
      echo "| ${eid} | ${title} | ${status} |"
    fi
  done
}

parse_todos() {
  python3 - "$REPO/.pi/todos" "$1" <<'PYEOF'
import sys, json, pathlib

todos_dir = pathlib.Path(sys.argv[1])
mode = sys.argv[2] if len(sys.argv) > 2 else "grouped"

def load_todo(f):
    text = f.read_text()
    lines = text.splitlines()
    json_lines = []
    for line in lines:
        json_lines.append(line)
        if line.strip() == '}':
            break
    try:
        return json.loads('\n'.join(json_lines))
    except json.JSONDecodeError:
        return None

todos = []
for f in sorted(todos_dir.glob("*.md")):
    meta = load_todo(f)
    if not meta:
        continue
    if meta.get("status") in ("open", "in-progress", "claimed"):
        todos.append(meta)

if mode == "bugs":
    for t in todos:
        if "bug" in t.get("tags", []):
            print(f"  - TODO-{t.get('id','?')[:8]}: {t.get('title','?')}")
    sys.exit(0)

# Grouped mode
groups = {"bugs": [], "planning": [], "creative": [], "other": []}
for t in todos:
    tags = t.get("tags", [])
    if "bug" in tags:
        groups["bugs"].append(t)
    elif any(tag in tags for tag in ("planning", "planning-infra")):
        groups["planning"].append(t)
    elif any(tag in tags for tag in ("creative", "art", "music")):
        groups["creative"].append(t)
    else:
        groups["other"].append(t)

for gname, items in groups.items():
    if not items:
        continue
    print(f"### {gname.capitalize()} ({len(items)})")
    print()
    for t in items:
        tid = t.get("id", "?")[:8]
        title = t.get("title", "(untitled)")
        status = t.get("status", "open")
        print(f"- TODO-{tid}: {title}  `{status}`")
    print()
PYEOF
}

# ---------------------------------------------------------------------------
# Build the document
# ---------------------------------------------------------------------------

{
echo "# Session Handover — $DATE"
echo ""
echo "_Auto-generated by \`scripts/handover.sh\` at $TIME. Do not edit by hand._"
echo ""

# --- 1. Branch State ---
echo "## 1. Branch State"
echo ""
echo "**Working tree:**"
echo '```'
git -C "$REPO" status --short 2>/dev/null || echo "(git status failed)"
echo '```'
echo ""
echo "**Branches:**"
echo '```'
git -C "$REPO" branch -a 2>/dev/null || echo "(git branch failed)"
echo '```'
echo ""
echo "**Recent commits (last 10):**"
echo '```'
git -C "$REPO" log --oneline -10 2>/dev/null || echo "(git log failed)"
echo '```'
echo ""

# --- 2. What Shipped Today ---
echo "## 2. What Shipped Today"
echo ""
SHIPPED="$(git -C "$REPO" log --oneline --since="24 hours ago" 2>/dev/null)"
if [ -z "$SHIPPED" ]; then
  echo "_No commits in the last 24 hours._"
else
  echo '```'
  echo "$SHIPPED"
  echo '```'
fi
echo ""

# --- 3. Epic Status ---
echo "## 3. Epic Status"
echo ""
echo "**Current branch:** \`$CURRENT_BRANCH\`"
echo ""
echo "| Epic | Title | Status |"
echo "|------|-------|--------|"
parse_epics ""
echo ""

# --- 4. Open Todos ---
echo "## 4. Open Todos"
echo ""
parse_todos "grouped"

# --- 5. Open GitHub Issues ---
echo "## 5. Open GitHub Issues"
echo ""
if command -v gh &>/dev/null 2>&1; then
  GH_OUT="$(gh issue list --state open --limit 20 2>/dev/null)" || GH_OUT=""
  if [ -n "$GH_OUT" ]; then
    echo '```'
    echo "$GH_OUT"
    echo '```'
  else
    echo "_No open issues, or gh list failed._"
  fi
else
  echo "_gh CLI not found — skipping._"
fi
echo ""

# --- 6. Recommended Next Steps ---
echo "## 6. Recommended Next Steps"
echo ""
echo "### In-progress epics"
echo ""
parse_epics "in-progress"
echo ""
echo "### Open bug todos"
echo ""
parse_todos "bugs"

} > "$OUT"

echo "Handover written to: $OUT"
wc -l < "$OUT" | xargs -I{} echo "{} lines"
