#!/usr/bin/env bash
# review-plan.sh — single haiku agent review of a scratch/plans/*.md file
# Usage: scripts/review-plan.sh scratch/plans/2026-03-23-w12-devlog-review.md
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$REPO_ROOT/scratch/plan-reviews"

FILE="${1:-}"
[[ -z "$FILE" ]] && { echo "Usage: $0 <plan-file>"; exit 1; }
[[ -f "$FILE" ]] || { echo "❌ Not found: $FILE"; exit 1; }
[[ -s "$FILE" ]] || { echo "⚠️  File is empty: $FILE"; exit 0; }
command -v claude >/dev/null 2>&1 || { echo "❌ claude CLI not found in PATH"; exit 1; }

mkdir -p "$OUT_DIR"
BASE=$(basename "$FILE" .md)
OUT="$OUT_DIR/${BASE}-review.md"

CONTENT=$(cat "$FILE")

echo "🔍 Reviewing $FILE with haiku agent…"

PROMPT=$(cat <<'PROMPT'
You are reviewing a WibWob-DOS weekly plan review. It contains tables or lists of ideas with ✅ (shipped) and ❌ (not done) status markers.

Analyse it across three lenses:

## Unblocked
Which ❌ Not-done items look actionable right now — no obvious unresolved dependency?
For each: name the item, then one sentence on what action would start it.
(Max 5 items. "None" if none.)

## Gaps
What pains or problems are IMPLIED by the ❌ pattern but not captured as any idea at all?
Suggest one new, atomic idea per gap.
(Max 3. "None" if none.)

## Redundant
Which ✅ Shipped items have close siblings still marked ❌ that may already be covered by the shipped work?
(Max 3. "None" if none.)

Keep it tight. Specific references to items in the source. No waffle.
PROMPT
)

echo "$CONTENT" | claude -p "$PROMPT" --model claude-haiku-4-5 > "$OUT.tmp"

{
  echo "# Plan Review: $BASE"
  echo ""
  echo "> Generated by \`scripts/review-plan.sh\` — $(date '+%Y-%m-%d %H:%M')"
  echo "> Source: \`$FILE\`"
  echo ""
  echo "---"
  echo ""
  cat "$OUT.tmp"
} > "$OUT"

rm -f "$OUT.tmp"
echo "✅ Review written to: $OUT"
