#!/usr/bin/env bash
# review-reflection.sh — multi-agent haiku review of a WXX reflection file
# Usage: scripts/review-reflection.sh W13
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REFLECTIONS_DIR="$REPO_ROOT/.pi/reflections"
OUT_DIR="$REPO_ROOT/scratch/reflection-reviews"

WEEK="${1:-}"
[[ -z "$WEEK" ]] && { echo "Usage: $0 WXX (e.g. W13)"; exit 1; }
command -v claude >/dev/null 2>&1 || { echo "❌ claude CLI not found in PATH"; exit 1; }

YEAR=$(date +%Y)
FILE="$REFLECTIONS_DIR/${YEAR}-${WEEK}.md"
[[ -f "$FILE" ]] || { echo "❌ Not found: $FILE"; exit 1; }
[[ -s "$FILE" ]] || { echo "⚠️  File is empty: $FILE"; exit 0; }

mkdir -p "$OUT_DIR"
OUT="$OUT_DIR/${YEAR}-${WEEK}-review.md"
TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

CONTENT=$(cat "$FILE")

echo "🔍 Reviewing $FILE with 2 parallel haiku agents…"

# Agent A — ideas audit
PROMPT_A=$(cat <<'PROMPT'
You are reviewing a WibWob-DOS agent reflection file. These are structured weekly notes with pain→why→fix→ideas entries.

Focus ONLY on "#### → Ideas" sections.

For each idea tagged [status:open]:
1. Does the surrounding Fix section suggest this was ALREADY shipped? If yes, note it as "likely-done".
2. Does any pain entry have NO "#### → Ideas" section at all? If yes, suggest ONE atomic buildable idea for it (a script, skill, command, or doc change — one sentence).

Return structured markdown with exactly two subsections:
## Open ideas that look shipped
(list any, or "None found")

## Pains missing → Ideas sections
(list with one suggested idea each, or "None found")

Keep it concise. No waffle.
PROMPT
)

# Agent B — pain pattern synthesis
PROMPT_B=$(cat <<'PROMPT'
You are reviewing a WibWob-DOS agent reflection file. These are structured weekly notes with pain→why→fix→ideas entries.

Identify the 3 most significant RECURRING pain themes across ALL entries in this file — not individual incidents, but clusters that appear more than once or point to the same root.

For each theme:
- One sentence naming the cluster
- One sentence on the root cause
- One atomic fix (a script, a doc change, a convention — specific and buildable)

Return as a markdown list of 3 items. No more than 3. No waffle.

## Recurring pain themes
PROMPT
)

echo "$CONTENT" | claude -p "$PROMPT_A" --model claude-haiku-4-5 > "$TMP/agent-a.md" &
PID_A=$!

echo "$CONTENT" | claude -p "$PROMPT_B" --model claude-haiku-4-5 > "$TMP/agent-b.md" &
PID_B=$!

wait $PID_A $PID_B

{
  echo "# Reflection Review: ${YEAR}-${WEEK}"
  echo ""
  echo "> Generated by \`scripts/review-reflection.sh\` — $(date '+%Y-%m-%d %H:%M')"
  echo "> Source: \`$FILE\`"
  echo ""
  echo "---"
  echo ""
  echo "## Agent A — Ideas Audit"
  echo ""
  cat "$TMP/agent-a.md"
  echo ""
  echo "---"
  echo ""
  echo "## Agent B — Pain Pattern Synthesis"
  echo ""
  cat "$TMP/agent-b.md"
} > "$OUT"

echo "✅ Review written to: $OUT"
